/// Generates an ungraded project evaluation card written to `EVALUATION.md` at scaffold time.
///
/// Teams fill in grades and notes as they build; the rubric ships with every new project so
/// quality expectations are visible from day one and carried into downstream Astropress projects.
pub(super) fn build_evaluation_rubric() -> String {
    format!(
        r#"# Project Evaluation Card

Generated by `astropress new` — fill in grades as you build.
This card carries the Astropress 54-rubric evaluation framework into each scaffolded project.
Grade scale: A+ / A / B / C / D / F

## Grades

| # | Rubric | Grade | Notes |
|---|--------|-------|-------|
| 1 | Spec Fidelity | | |
| 2 | Architecture Quality | | |
| 3 | Test Quality | | |
| 4 | Security Posture | | |
| 5 | Accessibility | | |
| 6 | Performance | | |
| 7 | Developer Ergonomics | | |
| 8 | Browser / Web API Usage | | |
| 9 | Web Components | | |
| 10 | Spec Coherence (WC First-Class) | | |
| 11 | CI/CD Pipeline | | |
| 12 | Dependency Management | | |
| 13 | Documentation | | |
| 14 | Observability / Logging | | |
| 15 | API Design | | |
| 16 | Error Handling | | |
| 17 | TypeScript Quality | | |
| 18 | AI Drivability | | |
| 19 | Internationalization (i18n) | | |
| 20 | SEO Tooling | | |
| 21 | AEO Tooling | | |
| 22 | First-Party Data | | |
| 23 | Content Modeling Flexibility | | |
| 24 | Schema Migration Safety | | |
| 25 | Caching Strategy | | |
| 26 | Plugin / Extension API | | |
| 27 | Image Optimization | | |
| 28 | Real-Time Collaboration | | |
| 29 | Privacy by Design | | |
| 30 | Open Source Health | | |
| 31 | Data Portability | | |
| 32 | Upgrade Path / Migration DX | | |
| 33 | Import / Migration Tooling | | |
| 34 | Content Scheduling | | |
| 35 | E2E Hosted Provider Testing | | |
| 36 | CLI UX Quality | | |
| 37 | Email Delivery | | |
| 38 | Search / Discovery | | |
| 39 | Admin CRUD E2E | | |
| 40 | Disaster Recovery | | |
| 41 | Monitoring Integration | | |
| 42 | Upgrade Path E2E | | |
| 43 | System Honesty | | |
| 44 | Multi-site Gateway (Nexus) | | |
| 45 | Scaffold Quality Carryover | | |
| 46 | Mobile-Firstness / Responsive Design | | |
| 47 | Admin Panel UX Quality | | |
| 48 | Nexus UX Quality | | |
| 49 | UX Writing & Microcopy | | |
| 50 | Information Architecture | | |
| 51 | Navigation Design | | |
| 52 | Interaction Design & Motion | | |
| 53 | Cross-Platform Support | | |
| 54 | Test Artifact Cleanup | | |

## What each rubric measures

### Core quality

| # | What to check |
|---|---------------|
| **1 — Spec Fidelity** | Implemented features match the original spec; no silent scope cuts |
| **2 — Architecture Quality** | Modules respect volatility boundaries; no god-file anti-patterns; LOC limits met |
| **3 — Test Quality** | Unit, integration, and E2E tests present; coverage meaningful; BDD scenarios verify user-facing behaviour |
| **4 — Security Posture** | ZTA on all admin actions; CSRF tokens; CSP headers; no raw `innerHTML`; secrets out of source |
| **5 — Accessibility** | WCAG 2.2 AA: keyboard nav, ARIA live regions, focus traps, colour contrast, screen-reader tested |
| **6 — Performance** | Core Web Vitals green on real hardware; LCP < 2.5 s; CLS = 0 on admin routes; images lazy-loaded |
| **7 — Developer Ergonomics** | Setup is ≤ 3 commands; public API surface is discoverable; error messages are actionable |

### Technical standards

| # | What to check |
|---|---------------|
| **8 — Browser / Web API Usage** | Prefer native APIs (Web Components, Fetch, `dialog`, `popover`) over polyfills |
| **9 — Web Components** | Custom elements registered spec-compliantly; no shadow-DOM leakage; lifecycle hooks correct |
| **10 — Spec Coherence** | Web Components treated as first-class in routing, SSR, hydration |
| **11 — CI/CD Pipeline** | Lint, type-check, test, and deploy gated on every push; no manual steps to ship |
| **12 — Dependency Management** | No unused packages; peer-dep conflicts absent; audit clean; update cadence documented |
| **17 — TypeScript Quality** | Strict mode; no `any` in public APIs; branded types for IDs and tokens |
| **53 — Cross-Platform Support** | Scaffold, CLI, docs, and release flow work on Windows, macOS, Linux, and documented BSD tiers; shell-specific steps are either avoided or explicitly supported |
| **54 — Test Artifact Cleanup** | Test and verification commands clean temporary directories and generated artifacts so reruns do not dirty the repo or require manual cleanup |

### Content & data

| # | What to check |
|---|---------------|
| **13 — Documentation** | README, QUICK_START, API reference, and inline JSDoc present and accurate |
| **14 — Observability / Logging** | Structured logs with severity; request IDs propagated; errors reported to monitoring |
| **15 — API Design** | REST endpoints resource-oriented; versioned; errors use RFC 7807 Problem Detail |
| **16 — Error Handling** | All `catch` blocks log context and re-throw or present a user-facing message; no swallowed errors |
| **22 — First-Party Data** | Analytics capture only what the site needs; no third-party pixels; GDPR erasure SQL included |
| **23 — Content Modeling** | Custom fields, taxonomies, and templates configurable without code changes |
| **24 — Schema Migration Safety** | Migrations are forward-only, incremental, tested against a copy of production data |
| **25 — Caching Strategy** | Static pages cached at CDN edge; API responses use `Cache-Control` with correct `Vary` |

### Publishing & reach

| # | What to check |
|---|---------------|
| **19 — Internationalization** | All user-facing strings externalised; RTL layout tested; date/number formats localised |
| **20 — SEO Tooling** | Canonical tags; Open Graph; `sitemap.xml`; `robots.txt`; structured data for articles |
| **21 — AEO Tooling** | FAQ, HowTo, BreadcrumbList, Speakable JSON-LD; `llms.txt`; DonateAction if fundraising |
| **27 — Image Optimization** | Automatic `srcset`, WebP, AVIF; lazy loading; no layout shift from unsized images |
| **34 — Content Scheduling** | Publish/unpublish at a future date; cron or build trigger configured |
| **37 — Email Delivery** | Transactional emails tested end-to-end with real SMTP |
| **38 — Search / Discovery** | Full-text search across content; search UI accessible; results ranked by relevance |

### Operations & reliability

| # | What to check |
|---|---------------|
| **18 — AI Drivability** | JSON doctor output; `--plain` on all CLI commands; `llms.txt`; structured logs |
| **26 — Plugin / Extension API** | Third-party integrations can be added without forking the framework |
| **28 — Real-Time Collaboration** | Concurrent editing conflicts detected and surfaced; presence indicators if applicable |
| **29 — Privacy by Design** | No telemetry by default; GDPR, CCPA, DNT/GPC respected; data minimisation documented |
| **30 — Open Source Health** | Licence clear; CONTRIBUTING guide; issue templates; security policy; changelogs |
| **31 — Data Portability** | Full export and import tested; no vendor lock-in on content data |
| **32 — Upgrade Path / Migration DX** | `astropress upgrade --check` catches breaking changes; upgrade guide published per version |
| **33 — Import / Migration Tooling** | WordPress/Wix import tested with real exports; media, redirects, and metadata preserved |
| **35 — E2E Hosted Provider Testing** | Adapter tests run against real cloud services in CI (not only mocks) |
| **39 — Admin CRUD E2E** | All create/read/update/delete flows covered by Playwright tests against a real running instance |
| **40 — Disaster Recovery** | Backup + restore tested on a clean environment; RTO documented |
| **41 — Monitoring Integration** | Health endpoint wired to uptime monitor; alerts configured for error-rate spikes |
| **42 — Upgrade Path E2E** | Automated test: create project on v(N−1), upgrade to v(N), assert content and config intact |
| **43 — System Honesty** | CLI, docs, and admin claims stay aligned with implementation; failures surface with context; no silent data loss |
| **44 — Multi-site Gateway (Nexus)** | `astropress-nexus` can proxy and manage multiple instances; health dashboard works |
| **45 — Scaffold Quality Carryover** | Security, a11y, privacy, and CI quality built into the scaffold — not added post-hoc |

### UX quality

| # | What to check |
|---|---------------|
| **36 — CLI UX Quality** | Commands follow `noun verb` pattern; `--help` accurate; `--plain` for CI; errors suggest fixes |
| **46 — Mobile-Firstness** | Layouts work at 320 px; touch targets ≥ 44×44 px; `min-width` breakpoints; responsive images |
| **47 — Admin Panel UX** | CRUD in ≤ 3 clicks; inline validation with specific messages; destructive actions gated; no data loss on back-button |
| **48 — Nexus UX** | Site list shows status at a glance; cross-site nav ≤ 2 clicks; bulk actions available |
| **49 — UX Writing** | Error messages identify problem + suggest fix; empty states have a CTA; buttons use verb phrases |
| **50 — Information Architecture** | Sidebar grouped by domain; settings separated from content; nav labels match user mental models |
| **51 — Navigation Design** | Persistent sidebar with active-page indicator; breadcrumbs at depth ≥ 2; skip-nav link present |
| **52 — Interaction Design** | Loading indicators within 100 ms; toasts auto-dismiss ≥ 4 s; CLS = 0; `prefers-reduced-motion` respected |

---

*This evaluation card was generated by `astropress new` v{version}. Update it as your project evolves.*
"#,
        version = env!("CARGO_PKG_VERSION")
    )
}
