//! Config file stubs for optional features.
//! Extracted from `feature_stubs.rs` to keep that file under the 300-line limit.

use crate::docs_stubs::docs_config_stubs;
use crate::features::{
    AllFeatures, CmsChoice, CommerceChoice, EmailChoice, PaymentChoice,
};
use crate::service_docs::service_compose_stubs;

// ── config file stubs ─────────────────────────────────────────────────────────

pub(crate) fn feature_config_stubs(f: &AllFeatures) -> Vec<(&'static str, &'static str)> {
    let mut files: Vec<(&'static str, &'static str)> = Vec::new();

    // Per-service docker-compose + .env.example files
    files.extend(service_compose_stubs(f));

    // Docs-site generator stubs (Starlight / VitePress / mdBook).
    files.extend(docs_config_stubs(f));

    match f.cms {
        CmsChoice::Keystatic => files.push((
            "keystatic.config.ts",
            "import { config } from '@keystatic/core';\n\nexport default config({\n  // Configure Keystatic here.\n  // See: https://keystatic.com/docs\n  collections: {},\n});\n",
        )),
        CmsChoice::Payload => files.push((
            "payload.config.ts",
            "import { buildConfig } from 'payload/config';\n\nexport default buildConfig({\n  // Configure Payload CMS here.\n  // See: https://payloadcms.com/docs/configuration/overview\n  collections: [],\n});\n",
        )),
        CmsChoice::BuiltIn => {}
    }
    if f.email == EmailChoice::Listmonk {
        // src/middleware.ts — overrides the static template to add registerAstropressService
        files.push(("src/middleware.ts", concat!(
            "import { createAstropressSecurityMiddleware } from \"astropress/integration\";\n",
            "import { registerCms } from \"astropress\";\n",
            "import { registerAstropressService } from \"astropress/services-config\";\n",
            "\n",
            "// Register CMS — edit siteUrl and templateKeys to match your site.\n",
            "// See: docs/guides/QUICK_START.md\n",
            "registerCms({\n",
            "  siteUrl: import.meta.env.SITE ?? \"https://example.com\",\n",
            "  templateKeys: [],\n",
            "  seedPages: [],\n",
            "  archives: [],\n",
            "  translationStatus: [],\n",
            "});\n",
            "\n",
            "// Register Listmonk so the admin panel can embed it at /ap-admin/services/email.\n",
            "// LISTMONK_API_URL is the public URL of your Listmonk instance (via the Caddy proxy).\n",
            "// See SERVICES.md for setup instructions.\n",
            "registerAstropressService({\n",
            "  provider: \"email\",\n",
            "  label: \"Listmonk\",\n",
            "  description: \"Newsletter and campaign management\",\n",
            "  adminPath: process.env.LISTMONK_API_URL ?? \"\",\n",
            "});\n",
            "\n",
            "// Applies security headers on every response:\n",
            "// CSP, X-Frame-Options, Permissions-Policy, Referrer-Policy, Cache-Control, X-Request-Id.\n",
            "// Options: https://astropress.dev/docs/reference/API_REFERENCE.md#security-middleware\n",
            "export const onRequest = createAstropressSecurityMiddleware();\n",
        )));

        // Listmonk compose files are now generated by service_docs::service_compose_stubs().
        // Setup instructions are in SERVICES.md (generated by service_docs::build_services_doc()).
    }
    if f.commerce == CommerceChoice::Medusa {
        files.push(("medusa-config.js",
            "/** @type {import('@medusajs/medusa').ConfigModule} */\nmodule.exports = {\n  projectConfig: { databaseUrl: process.env.DATABASE_URL },\n  plugins: [],\n};\n",
        ));
    }
    if f.payments == PaymentChoice::HyperSwitch {
        // HyperCheckout.astro — Unified Checkout form that handles M-Pesa STK Push,
        // UPI (Razorpay/Cashfree/PayU/PhonePe), cards, Apple Pay, Google Pay, and every
        // other method enabled in the HyperSwitch connector dashboard.
        // MIT: https://github.com/juspay/hyperswitch-web
        files.push(("src/components/HyperCheckout.astro", concat!(
            "---\n",
            "// HyperSwitch Unified Checkout — https://github.com/juspay/hyperswitch-web (MIT)\n",
            "//\n",
            "// Mounts a pre-built checkout form that auto-selects the right UI based on\n",
            "// the connectors you have enabled in the HyperSwitch dashboard:\n",
            "//   • M-Pesa: phone-number field → Safaricom STK Push PIN prompt on the user's phone\n",
            "//   • UPI (Razorpay / Cashfree / PayU / PhonePe): VPA field + collect flow\n",
            "//   • Cards / Apple Pay / Google Pay: standard card form or native sheet\n",
            "//\n",
            "// Usage — create a PaymentIntent server-side first:\n",
            "//\n",
            "//   // src/pages/api/create-payment.ts\n",
            "//   export const POST: APIRoute = async ({ request }) => {\n",
            "//     const { amount, currency } = await request.json();   // amount in minor units (e.g. 100 = KES 1.00)\n",
            "//     const res = await fetch(`${import.meta.env.HYPERSWITCH_BASE_URL}/payments`, {\n",
            "//       method: \"POST\",\n",
            "//       headers: { \"Content-Type\": \"application/json\", \"api-key\": import.meta.env.HYPERSWITCH_API_KEY },\n",
            "//       body: JSON.stringify({ amount, currency, confirm: false }),\n",
            "//     });\n",
            "//     const { client_secret } = await res.json();\n",
            "//     return new Response(JSON.stringify({ client_secret }), {\n",
            "//       headers: { \"Content-Type\": \"application/json\" },\n",
            "//     });\n",
            "//   };\n",
            "//\n",
            "// Then render this component on your checkout page:\n",
            "//   <HyperCheckout clientSecret={clientSecret} returnUrl=\"https://yourdomain.com/payment/done\" />\n",
            "\n",
            "interface Props {\n",
            "  clientSecret: string;\n",
            "  returnUrl: string;\n",
            "  /** Optional appearance config — https://hyperswitch.io/docs/sdkIntegrations/unifiedCheckoutWeb/customization */\n",
            "  appearance?: Record<string, unknown>;\n",
            "}\n",
            "const { clientSecret, returnUrl, appearance = {} } = Astro.props;\n",
            "const publishableKey = import.meta.env.HYPERSWITCH_PUBLISHABLE_KEY;\n",
            "---\n",
            "<div id=\"hs-unified-checkout\"></div>\n",
            "<button id=\"hs-pay-btn\" type=\"button\">Pay now</button>\n",
            "\n",
            "<script define:vars={{ clientSecret, returnUrl, publishableKey, appearance }}>\n",
            "  const s = document.createElement(\"script\");\n",
            "  s.src = \"https://beta.hyperswitch.io/v1/HyperLoader.js\";\n",
            "  s.onload = () => {\n",
            "    const hyper = window.Hyper(publishableKey);\n",
            "    const elements = hyper.elements({ clientSecret, appearance });\n",
            "    const checkout = elements.create(\"payment\");\n",
            "    checkout.mount(\"#hs-unified-checkout\");\n",
            "\n",
            "    document.getElementById(\"hs-pay-btn\")?.addEventListener(\"click\", async () => {\n",
            "      const { error } = await hyper.confirmPayment({\n",
            "        elements,\n",
            "        confirmParams: { return_url: returnUrl },\n",
            "      });\n",
            "      if (error) {\n",
            "        // Show error.message to the user — e.g. update a <p id=\"hs-error\"> element.\n",
            "        console.error(error.message);\n",
            "      }\n",
            "    });\n",
            "  };\n",
            "  document.head.appendChild(s);\n",
            "</script>\n",
        )));
    }
    if f.job_board {
        files.push(("content-types.example.ts", concat!(
            "// Uncomment and pass to registerCms({ contentTypes: [jobListingContentType] }).\n",
            "// export const jobListingContentType = {\n",
            "//   key: \"job\",\n",
            "//   label: \"Job Listing\",\n",
            "//   fields: [\n",
            "//     { name: \"company\",  label: \"Company\",         type: \"text\",   required: true },\n",
            "//     { name: \"location\", label: \"Location\",        type: \"text\" },\n",
            "//     { name: \"salary\",   label: \"Salary Range\",    type: \"text\" },\n",
            "//     { name: \"jobType\",  label: \"Type\",            type: \"select\",\n",
            "//       options: [\"full-time\",\"part-time\",\"contract\",\"remote\"] },\n",
            "//     { name: \"applyUrl\", label: \"Apply URL\",       type: \"text\" },\n",
            "//   ],\n",
            "// };\n",
        )));
    }
    files
}
