import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: [
      { find: "astropress", replacement: fileURLToPath(new URL("./index.ts", import.meta.url)) },
      { find: "cloudflare:workers", replacement: fileURLToPath(new URL("./src/cloudflare-workers-stub.ts", import.meta.url)) },
    ],
  },
  test: {
    setupFiles: ["tests/setup/html-rewriter-polyfill.ts"],
    include: ["tests/**/*.test.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary", "json"],
      reportsDirectory: "./coverage",
      include: [
        "src/admin-action-utils.js",
        "src/admin-routes.js",
        "src/admin-ui.js",
        "src/cloudflare-vite-integration.js",
        "src/config.js",
        "src/crypto-utils.js",
        "src/hosted-api-adapter.js",
        "src/hosted-platform-adapter.js",
        "src/html-optimization.ts",
        "src/html-sanitization.ts",
        "src/integration.js",
        "src/locale-links.ts",
        "src/media.ts",
        "src/project-env.js",
        "src/project-launch.js",
        "src/project-runtime.js",
        "src/project-scaffold.js",
        "src/provider-choice.js",
        "src/provider-targets.ts",
        "src/security-headers.js",
        "src/security-middleware.js",
        "src/site-settings.js",
        "src/vite-runtime-alias.js",
        "src/vitest-runtime-alias.js",
        "src/sqlite-admin-runtime.js",
        "src/sqlite-runtime/utils.js",
        "src/sqlite-runtime/auth.js",
        "src/sqlite-runtime/settings.js",
        "src/sqlite-runtime/content.js",
        "src/sqlite-runtime/catalog.js",
        "src/sqlite-runtime/routes.js",
        "src/sqlite-runtime/assets.js",
        "src/import/wordpress.js",
        "src/deploy/github-pages.js",
        "src/deploy/shared.js",
        "src/deploy/netlify.js",
        "src/deploy/vercel.js",
        "src/deploy/cloudflare-pages.js",
        "src/deploy/render.js",
        "src/deploy/firebase-hosting.js",
        "src/deploy/gitlab-pages.js",
        "src/deploy/custom.js",
        "src/adapters/cloudflare.js",
        "src/adapters/hosted.js",
        "src/adapters/local.js",
        "src/adapters/project.js",
        "src/adapters/runway.js",
        "src/adapters/runway-sqlite.js",
        "src/adapters/supabase.js",
        "src/adapters/supabase-sqlite.js",
        "src/runtime-admin-actions.ts",
        "src/newsletter-adapter.ts",
        "src/local-media-storage.js",
        "src/sync/git.js",
        "src/admin-page-models.ts",
        "src/runtime-route-registry.ts",
        "src/services-config.js",
      ],
      exclude: [
        "src/cloudflare-*-stub.*",
        "src/client/**/*.ts",
        "src/local-runtime-modules.ts",
        "src/**/*.d.ts",
      ],
      thresholds: {
        lines: 97,
        functions: 97,
        branches: 97,
        statements: 97,
      },
    },
  },
});
