import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    extensionAlias: {
      ".js": [".ts", ".js"],
    },
    alias: [
      { find: "astropress", replacement: fileURLToPath(new URL("./index.ts", import.meta.url)) },
      { find: "cloudflare:workers", replacement: fileURLToPath(new URL("./src/cloudflare-workers-stub.ts", import.meta.url)) },
    ],
  },
  test: {
    setupFiles: ["tests/setup/html-rewriter-polyfill.ts"],
    include: ["tests/**/*.test.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary", "json"],
      reportsDirectory: "./coverage",
      include: [
        "src/admin-action-utils.ts",
        "src/admin-normalizers.ts",
        "src/d1-admin-store.ts",
        "src/admin-routes.ts",
        "src/admin-ui.ts",
        "src/cloudflare-vite-integration.ts",
        "src/config.ts",
        "src/crypto-utils.ts",
        "src/hosted-api-adapter.ts",
        "src/hosted-platform-adapter.ts",
        "src/html-optimization.ts",
        "src/html-sanitization.ts",
        "src/integration.ts",
        "src/locale-links.ts",
        "src/media.ts",
        "src/project-env.ts",
        "src/project-launch.ts",
        "src/project-runtime.ts",
        "src/project-scaffold.ts",
        "src/provider-choice.ts",
        "src/provider-targets.ts",
        "src/security-headers.ts",
        "src/security-middleware.ts",
        "src/site-settings.ts",
        "src/vite-runtime-alias.ts",
        "src/vitest-runtime-alias.ts",
        "src/sqlite-admin-runtime.ts",
        "src/sqlite-runtime/utils.ts",
        "src/sqlite-runtime/auth.ts",
        "src/sqlite-runtime/settings.ts",
        "src/sqlite-runtime/content.ts",
        "src/sqlite-runtime/catalog.ts",
        "src/sqlite-runtime/routes.ts",
        "src/sqlite-runtime/assets.ts",
        "src/import/wordpress.ts",
        "src/deploy/github-pages.ts",
        "src/deploy/shared.ts",
        "src/deploy/netlify.ts",
        "src/deploy/vercel.ts",
        "src/deploy/cloudflare-pages.ts",
        "src/deploy/render.ts",
        "src/deploy/firebase-hosting.ts",
        "src/deploy/gitlab-pages.ts",
        "src/deploy/custom.ts",
        "src/adapters/cloudflare.ts",
        "src/adapters/hosted.ts",
        "src/adapters/local.ts",
        "src/adapters/project.ts",
        "src/adapters/runway.ts",
        "src/adapters/runway-sqlite.ts",
        "src/adapters/supabase.ts",
        "src/adapters/supabase-sqlite.ts",
        "src/runtime-admin-actions.ts",
        "src/runtime-actions-content.ts",
        "src/runtime-actions-users.ts",
        "src/runtime-actions-media.ts",
        "src/runtime-actions-taxonomies.ts",
        "src/runtime-actions-misc.ts",
        "src/newsletter-adapter.ts",
        "src/local-media-storage.ts",
        "src/sync/git.ts",
        "src/admin-page-models.ts",
        "src/runtime-route-registry.ts",
        "src/runtime-route-registry-system.ts",
        "src/runtime-route-registry-pages.ts",
        "src/runtime-route-registry-archives.ts",
        "src/d1-store-content.ts",
        "src/d1-store-taxonomies.ts",
        "src/d1-store-operations.ts",
        "src/admin-store-dispatch.ts",
        "src/d1-audit.ts",
        "src/services-config.ts",
        "src/analytics.ts",
        "src/api-middleware.ts",
        "src/api-routes.ts",
      ],
      exclude: [
        "src/cloudflare-*-stub.*",
        "src/client/**/*.ts",
        "src/local-runtime-modules.ts",
        "src/**/*.d.ts",
      ],
      thresholds: {
        lines: 95,
        functions: 95,
        branches: 85,
        statements: 95,
      },
    },
  },
});
