export type AdminLocale = "en" | "es" | "fr" | "de" | "pt" | "ja";

export type AdminLabelKey =
  | "loginHeading"
  | "themeToggleDark"
  | "themeToggleLight"
  | "saveButton"
  | "publishButton"
  | "discardButton"
  | "deleteButton"
  | "cancelButton"
  | "signOut"
  | "sidebarTitle"
  | "createPost"
  | "editPost"
  | "createPage"
  | "editPage"
  | "archivePost"
  | "restorePost"
  | "duplicatePost"
  | "navDashboard"
  | "navPosts"
  | "navPages"
  | "navMedia"
  | "navComments"
  | "navAuthors"
  | "navTaxonomies"
  | "navRedirects"
  | "navTranslations"
  | "navSeo"
  | "navUsers"
  | "navSettings"
  | "navSystem"
  | "navApiTokens"
  | "navWebhooks"
  | "uploadMedia"
  | "chooseFile"
  | "altTextLabel"
  | "approveComment"
  | "rejectComment"
  | "pendingModeration"
  | "searchPlaceholder"
  | "noResults"
  | "confirmDelete"
  | "changeLanguage"
  | "loadingLabel"
  | "errorLabel";

export const adminLabels: Record<AdminLocale, Record<AdminLabelKey, string>> = {
  en: {
    loginHeading: "Sign in to the admin",
    themeToggleDark: "Switch to dark mode",
    themeToggleLight: "Switch to light mode",
    saveButton: "Save",
    publishButton: "Publish",
    discardButton: "Discard",
    deleteButton: "Delete",
    cancelButton: "Cancel",
    signOut: "Sign out",
    sidebarTitle: "Workspace",
    createPost: "New post",
    editPost: "Edit post",
    createPage: "New page",
    editPage: "Edit page",
    archivePost: "Archive",
    restorePost: "Restore",
    duplicatePost: "Duplicate",
    navDashboard: "Dashboard",
    navPosts: "Posts",
    navPages: "Pages",
    navMedia: "Media",
    navComments: "Comments",
    navAuthors: "Authors",
    navTaxonomies: "Categories & Tags",
    navRedirects: "Redirects",
    navTranslations: "Translations",
    navSeo: "SEO",
    navUsers: "Users",
    navSettings: "Settings",
    navSystem: "System",
    navApiTokens: "API Tokens",
    navWebhooks: "Webhooks",
    uploadMedia: "Upload media",
    chooseFile: "Choose file",
    altTextLabel: "Alt text",
    approveComment: "Approve",
    rejectComment: "Reject",
    pendingModeration: "Pending moderation",
    searchPlaceholder: "Search\u2026",
    noResults: "No results found",
    confirmDelete: "Are you sure you want to delete this? This action cannot be undone.",
    changeLanguage: "Change language",
    loadingLabel: "Loading\u2026",
    errorLabel: "Action failed",
  },
  es: {
    loginHeading: "Acceder al panel de administraci\u00f3n",
    themeToggleDark: "Cambiar a modo oscuro",
    themeToggleLight: "Cambiar a modo claro",
    saveButton: "Guardar",
    publishButton: "Publicar",
    discardButton: "Descartar",
    deleteButton: "Eliminar",
    cancelButton: "Cancelar",
    signOut: "Cerrar sesi\u00f3n",
    sidebarTitle: "Espacio de trabajo",
    createPost: "Nueva entrada",
    editPost: "Editar entrada",
    createPage: "Nueva p\u00e1gina",
    editPage: "Editar p\u00e1gina",
    archivePost: "Archivar",
    restorePost: "Restaurar",
    duplicatePost: "Duplicar",
    navDashboard: "Panel",
    navPosts: "Entradas",
    navPages: "P\u00e1ginas",
    navMedia: "Medios",
    navComments: "Comentarios",
    navAuthors: "Autores",
    navTaxonomies: "Categor\u00edas y etiquetas",
    navRedirects: "Redirecciones",
    navTranslations: "Traducciones",
    navSeo: "SEO",
    navUsers: "Usuarios",
    navSettings: "Configuraci\u00f3n",
    navSystem: "Sistema",
    navApiTokens: "Tokens de API",
    navWebhooks: "Webhooks",
    uploadMedia: "Subir archivo",
    chooseFile: "Elegir archivo",
    altTextLabel: "Texto alternativo",
    approveComment: "Aprobar",
    rejectComment: "Rechazar",
    pendingModeration: "Pendiente de moderaci\u00f3n",
    searchPlaceholder: "Buscar\u2026",
    noResults: "No se encontraron resultados",
    confirmDelete: "\u00bfSeguro que quieres eliminar esto? Esta acci\u00f3n no se puede deshacer.",
    changeLanguage: "Cambiar idioma",
    loadingLabel: "Cargando\u2026",
    errorLabel: "Se produjo un error",
  },
  fr: {
    loginHeading: "Se connecter \u00e0 l'administration",
    themeToggleDark: "Passer en mode sombre",
    themeToggleLight: "Passer en mode clair",
    saveButton: "Enregistrer",
    publishButton: "Publier",
    discardButton: "Ignorer",
    deleteButton: "Supprimer",
    cancelButton: "Annuler",
    signOut: "Se d\u00e9connecter",
    sidebarTitle: "Espace de travail",
    createPost: "Nouvel article",
    editPost: "Modifier l'article",
    createPage: "Nouvelle page",
    editPage: "Modifier la page",
    archivePost: "Archiver",
    restorePost: "Restaurer",
    duplicatePost: "Dupliquer",
    navDashboard: "Tableau de bord",
    navPosts: "Articles",
    navPages: "Pages",
    navMedia: "M\u00e9dias",
    navComments: "Commentaires",
    navAuthors: "Auteurs",
    navTaxonomies: "Cat\u00e9gories et \u00e9tiquettes",
    navRedirects: "Redirections",
    navTranslations: "Traductions",
    navSeo: "SEO",
    navUsers: "Utilisateurs",
    navSettings: "Param\u00e8tres",
    navSystem: "Syst\u00e8me",
    navApiTokens: "Jetons API",
    navWebhooks: "Webhooks",
    uploadMedia: "T\u00e9l\u00e9verser un fichier",
    chooseFile: "Choisir un fichier",
    altTextLabel: "Texte alternatif",
    approveComment: "Approuver",
    rejectComment: "Rejeter",
    pendingModeration: "En attente de mod\u00e9ration",
    searchPlaceholder: "Rechercher\u2026",
    noResults: "Aucun r\u00e9sultat trouv\u00e9",
    confirmDelete: "Voulez-vous vraiment supprimer ceci\u00a0? Cette action est irr\u00e9versible.",
    changeLanguage: "Changer de langue",
    loadingLabel: "Chargement\u2026",
    errorLabel: "Une erreur est survenue",
  },
  de: {
    loginHeading: "Beim Admin anmelden",
    themeToggleDark: "Zum Dunkelmodus wechseln",
    themeToggleLight: "Zum Hellmodus wechseln",
    saveButton: "Speichern",
    publishButton: "Ver\u00f6ffentlichen",
    discardButton: "Verwerfen",
    deleteButton: "L\u00f6schen",
    cancelButton: "Abbrechen",
    signOut: "Abmelden",
    sidebarTitle: "Arbeitsbereich",
    createPost: "Neuer Beitrag",
    editPost: "Beitrag bearbeiten",
    createPage: "Neue Seite",
    editPage: "Seite bearbeiten",
    archivePost: "Archivieren",
    restorePost: "Wiederherstellen",
    duplicatePost: "Duplizieren",
    navDashboard: "Dashboard",
    navPosts: "Beitr\u00e4ge",
    navPages: "Seiten",
    navMedia: "Medien",
    navComments: "Kommentare",
    navAuthors: "Autoren",
    navTaxonomies: "Kategorien & Tags",
    navRedirects: "Weiterleitungen",
    navTranslations: "\u00dcbersetzungen",
    navSeo: "SEO",
    navUsers: "Benutzer",
    navSettings: "Einstellungen",
    navSystem: "System",
    navApiTokens: "API-Token",
    navWebhooks: "Webhooks",
    uploadMedia: "Datei hochladen",
    chooseFile: "Datei ausw\u00e4hlen",
    altTextLabel: "Alternativtext",
    approveComment: "Genehmigen",
    rejectComment: "Ablehnen",
    pendingModeration: "Ausstehende Moderation",
    searchPlaceholder: "Suchen\u2026",
    noResults: "Keine Ergebnisse gefunden",
    confirmDelete: "M\u00f6chten Sie dies wirklich l\u00f6schen? Diese Aktion kann nicht r\u00fcckg\u00e4ngig gemacht werden.",
    changeLanguage: "Sprache \u00e4ndern",
    loadingLabel: "Wird geladen\u2026",
    errorLabel: "Ein Fehler ist aufgetreten",
  },
  pt: {
    loginHeading: "Entrar no painel de administra\u00e7\u00e3o",
    themeToggleDark: "Mudar para modo escuro",
    themeToggleLight: "Mudar para modo claro",
    saveButton: "Salvar",
    publishButton: "Publicar",
    discardButton: "Descartar",
    deleteButton: "Excluir",
    cancelButton: "Cancelar",
    signOut: "Sair",
    sidebarTitle: "\u00c1rea de trabalho",
    createPost: "Nova publica\u00e7\u00e3o",
    editPost: "Editar publica\u00e7\u00e3o",
    createPage: "Nova p\u00e1gina",
    editPage: "Editar p\u00e1gina",
    archivePost: "Arquivar",
    restorePost: "Restaurar",
    duplicatePost: "Duplicar",
    navDashboard: "Painel",
    navPosts: "Publica\u00e7\u00f5es",
    navPages: "P\u00e1ginas",
    navMedia: "M\u00eddia",
    navComments: "Coment\u00e1rios",
    navAuthors: "Autores",
    navTaxonomies: "Categorias e tags",
    navRedirects: "Redirecionamentos",
    navTranslations: "Tradu\u00e7\u00f5es",
    navSeo: "SEO",
    navUsers: "Usu\u00e1rios",
    navSettings: "Configura\u00e7\u00f5es",
    navSystem: "Sistema",
    navApiTokens: "Tokens de API",
    navWebhooks: "Webhooks",
    uploadMedia: "Carregar arquivo",
    chooseFile: "Escolher arquivo",
    altTextLabel: "Texto alternativo",
    approveComment: "Aprovar",
    rejectComment: "Rejeitar",
    pendingModeration: "Aguardando modera\u00e7\u00e3o",
    searchPlaceholder: "Pesquisar\u2026",
    noResults: "Nenhum resultado encontrado",
    confirmDelete: "Tem certeza que quer excluir isso? Esta a\u00e7\u00e3o n\u00e3o pode ser desfeita.",
    changeLanguage: "Alterar idioma",
    loadingLabel: "Carregando\u2026",
    errorLabel: "Ocorreu um erro",
  },
  ja: {
    loginHeading: "\u7ba1\u7406\u30d1\u30cd\u30eb\u306b\u30b5\u30a4\u30f3\u30a4\u30f3",
    themeToggleDark: "\u30c0\u30fc\u30af\u30e2\u30fc\u30c9\u306b\u5207\u308a\u66ff\u3048",
    themeToggleLight: "\u30e9\u30a4\u30c8\u30e2\u30fc\u30c9\u306b\u5207\u308a\u66ff\u3048",
    saveButton: "\u4fdd\u5b58",
    publishButton: "\u516c\u958b",
    discardButton: "\u7834\u68c4",
    deleteButton: "\u524a\u9664",
    cancelButton: "\u30ad\u30e3\u30f3\u30bb\u30eb",
    signOut: "\u30b5\u30a4\u30f3\u30a2\u30a6\u30c8",
    sidebarTitle: "\u30ef\u30fc\u30af\u30b9\u30da\u30fc\u30b9",
    createPost: "\u65b0\u3057\u3044\u6295\u7a3f",
    editPost: "\u6295\u7a3f\u3092\u7de8\u96c6",
    createPage: "\u65b0\u3057\u3044\u30da\u30fc\u30b8",
    editPage: "\u30da\u30fc\u30b8\u3092\u7de8\u96c6",
    archivePost: "\u30a2\u30fc\u30ab\u30a4\u30d6",
    restorePost: "\u5fa9\u5143",
    duplicatePost: "\u8907\u88fd",
    navDashboard: "\u30c0\u30c3\u30b7\u30e5\u30dc\u30fc\u30c9",
    navPosts: "\u6295\u7a3f",
    navPages: "\u30da\u30fc\u30b8",
    navMedia: "\u30e1\u30c7\u30a3\u30a2",
    navComments: "\u30b3\u30e1\u30f3\u30c8",
    navAuthors: "\u8457\u8005",
    navTaxonomies: "\u30ab\u30c6\u30b4\u30ea\u3068\u30bf\u30b0",
    navRedirects: "\u30ea\u30c0\u30a4\u30ec\u30af\u30c8",
    navTranslations: "\u7ffb\u8a33",
    navSeo: "SEO",
    navUsers: "\u30e6\u30fc\u30b6\u30fc",
    navSettings: "\u8a2d\u5b9a",
    navSystem: "\u30b7\u30b9\u30c6\u30e0",
    navApiTokens: "API\u30c8\u30fc\u30af\u30f3",
    navWebhooks: "Webhook",
    uploadMedia: "\u30d5\u30a1\u30a4\u30eb\u3092\u30a2\u30c3\u30d7\u30ed\u30fc\u30c9",
    chooseFile: "\u30d5\u30a1\u30a4\u30eb\u3092\u9078\u629e",
    altTextLabel: "\u4ee3\u66ff\u30c6\u30ad\u30b9\u30c8",
    approveComment: "\u627f\u8a8d",
    rejectComment: "\u5374\u4e0b",
    pendingModeration: "\u30e2\u30c7\u30ec\u30fc\u30c8\u5f85\u3061",
    searchPlaceholder: "\u691c\u7d22\u2026",
    noResults: "\u7d50\u679c\u304c\u898b\u3064\u304b\u308a\u307e\u305b\u3093",
    confirmDelete: "\u672c\u5f53\u306b\u524a\u9664\u3057\u307e\u3059\u304b\uff1f\u3053\u306e\u64cd\u4f5c\u306f\u5143\u306b\u623b\u305b\u307e\u305b\u3093\u3002",
    changeLanguage: "\u8a00\u8a9e\u3092\u5909\u66f4",
    loadingLabel: "\u8aad\u307f\u8fbc\u307f\u4e2d\u2026",
    errorLabel: "\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f",
  },
};
