export type AdminLocale =
	| "en"
	| "es"
	| "fr"
	| "de"
	| "pt"
	| "ja"
	| "te"
	| "hi"
	| "ny"
	| "ar";

export type AdminLabelKey =
	| "loginHeading"
	| "loginDescription"
	| "loginSubmit"
	| "loginEmailLabel"
	| "loginPasswordLabel"
	| "forgotPassword"
	| "invalidCredentials"
	| "rateLimited"
	| "challengeRequired"
	| "passwordResetSuccess"
	| "invitationAcceptedSuccess"
	| "acceptInvitationHeading"
	| "acceptInvitationDescription"
	| "acceptInvitationSubmit"
	| "resetPasswordRequestHeading"
	| "resetPasswordRequestDescription"
	| "resetPasswordTokenHeading"
	| "resetPasswordTokenDescription"
	| "resetPasswordRequestSubmit"
	| "resetPasswordTokenSubmit"
	| "backToLogin"
	| "themeToggleDark"
	| "themeToggleLight"
	| "signOut"
	| "signedInAsPrefix"
	| "sidebarTitle"
	| "navDashboard"
	| "navContentGroup"
	| "navPosts"
	| "navPages"
	| "navMedia"
	| "navComments"
	| "navAuthors"
	| "navTaxonomies"
	| "navRoutePages"
	| "navArchives"
	| "navRedirects"
	| "navTranslations"
	| "navSeo"
	| "navUsers"
	| "navAccess"
	| "navSettings"
	| "navSystem"
	| "navApiTokens"
	| "navWebhooks"
	| "navServices"
	| "navFundraising"
	| "navTestimonials"
	| "navCms"
	| "navHost"
	// Group labels (added in IA restructure)
	| "navGroupSite"
	| "navGroupAudience"
	| "navGroupComingSoon"
	| "navGroupAccess"
	// Site
	| "navForms"
	// Content
	// Audience
	| "navSubscribers"
	| "navNewsletter"
	| "navEvents"
	| "navReviews"
	| "navReferrals"
	| "navMemberships"
	| "navCommunity"
	| "navShop"
	// Discoverability
	| "navStructuredData"
	| "navSitemaps"
	| "navMapsLocal"
	// Integrations
	| "navAnalytics"
	| "navHeatmaps"
	| "navAbTesting"
	| "navEmail"
	| "navLiveChat"
	| "navImageCdn"
	| "navSearch"
	| "navCdnPurge"
	| "navMonitoring"
	| "navDeployHooks"
	| "navPlugins"
	// Operations
	| "navData"
	| "navBackups"
	// RequiresIntegration stub component
	| "stubNotConfiguredHeading"
	| "stubHowToEnable"
	| "stubSupportedProviders"
	| "stubLearnMore"
	| "stubComingSoonHeading"
	| "stubComingSoonBody"
	| "stubComingSoonLink"
	| "changeLanguage"
	| "approveComment"
	| "cancelButton"
	| "confirmDelete"
	| "createPost"
	| "deleteButton"
	| "errorLabel"
	| "loadingLabel"
	| "publishButton"
	| "saveButton"
	| "navGroupDiscoverability"
	| "navGroupIntegrations"
	| "navGroupOperations"
	| "navHeadlessCmsPanel"
	| "navSocialSyndication";

/**
 * Every locale must define every AdminLabelKey. This is enforced at the type
 * level — adding a new key to the union without translating it for every
 * locale is a compile-time error. `getAdminLabel()` still falls back to
 * English at runtime as a defense-in-depth guard, but the strict typing
 * here is the primary leak prevention mechanism.
 */
export const adminLabels: Record<AdminLocale, Record<AdminLabelKey, string>> = {
	en: {
		loginHeading: "Sign in to the admin",
		loginDescription:
			"Use an approved admin account to manage content, media, redirects, and publishing settings.",
		loginSubmit: "Sign in",
		loginEmailLabel: "Email address",
		loginPasswordLabel: "Password",
		forgotPassword: "Forgot your password?",
		invalidCredentials:
			"That email and password combination was not recognized.",
		rateLimited:
			"Too many sign-in attempts were recorded. Wait a minute and try again.",
		challengeRequired:
			"Complete the security challenge and try signing in again.",
		passwordResetSuccess:
			"Your password was reset successfully. Sign in with the new password.",
		invitationAcceptedSuccess:
			"Your invitation was accepted successfully. Sign in with the new password.",
		acceptInvitationHeading: "Accept invitation",
		acceptInvitationDescription:
			"Set a password to activate this invited admin account.",
		acceptInvitationSubmit: "Accept invitation",
		resetPasswordRequestHeading: "Reset password",
		resetPasswordRequestDescription:
			"Enter your admin email address and Astropress will issue a password reset link if the account exists.",
		resetPasswordTokenHeading: "Choose a new password",
		resetPasswordTokenDescription: "Set a new password for this admin account.",
		resetPasswordRequestSubmit: "Issue reset link",
		resetPasswordTokenSubmit: "Save new password",
		backToLogin: "Back to admin login",
		themeToggleDark: "Switch to dark mode",
		themeToggleLight: "Switch to light mode",
		signOut: "Sign out",
		signedInAsPrefix: "Signed in as",
		sidebarTitle: "Workspace",
		navDashboard: "Dashboard",
		navContentGroup: "Content",
		navPosts: "Posts",
		navPages: "Pages",
		navMedia: "Media",
		navComments: "Comments",
		navAuthors: "Authors",
		navTaxonomies: "Categories & Tags",
		navRoutePages: "Route Table",
		navArchives: "Archives",
		navRedirects: "Redirects",
		navTranslations: "Translations",
		navSeo: "SEO",
		navUsers: "Users",
		navAccess: "Access",
		navSettings: "Settings",
		navSystem: "System",
		navApiTokens: "API Tokens",
		navWebhooks: "Webhooks",
		navServices: "Services",
		navFundraising: "Fundraising",
		navTestimonials: "Testimonials",
		navCms: "CMS",
		navHost: "Host",
		navGroupSite: "Site",
		navGroupAudience: "Audience",
		navGroupComingSoon: "Coming soon",
		navGroupAccess: "Access",
		navForms: "Forms",
		navSubscribers: "Subscribers",
		navNewsletter: "Newsletter",
		navEvents: "Events",
		navReviews: "Reviews",
		navReferrals: "Referrals",
		navMemberships: "Memberships",
		navCommunity: "Community",
		navShop: "Shop",
		navStructuredData: "Structured Data / AEO",
		navSitemaps: "Sitemaps",
		navMapsLocal: "Maps & Local",
		navAnalytics: "Analytics",
		navHeatmaps: "Heatmaps & Session Replay",
		navAbTesting: "A/B Testing & Feature Flags",
		navEmail: "Email",
		navLiveChat: "Live Chat",
		navImageCdn: "Image CDN",
		navSearch: "Search",
		navCdnPurge: "CDN Purge",
		navMonitoring: "Monitoring",
		navDeployHooks: "Deploy Hooks",
		navPlugins: "Plugins",
		navData: "Data",
		navBackups: "Backups",
		stubNotConfiguredHeading: "Not configured yet",
		stubHowToEnable: "How to enable",
		stubSupportedProviders: "Supported providers",
		stubLearnMore: "Learn more",
		stubComingSoonHeading: "Coming soon",
		stubComingSoonBody:
			"This integration is on the roadmap but not yet implemented.",
		stubComingSoonLink: "Track progress on GitHub",
		confirmDelete:
			"Are you sure you want to delete this? This action cannot be undone.",
		changeLanguage: "Change language",
		approveComment: "Approve",
		cancelButton: "Cancel",
		createPost: "New post",
		deleteButton: "Delete",
		errorLabel: "Action failed",
		loadingLabel: "Loading…",
		publishButton: "Publish",
		saveButton: "Save",
		navGroupDiscoverability: "Discoverability",
		navGroupIntegrations: "Integrations",
		navGroupOperations: "Operations",
		navHeadlessCmsPanel: "Headless CMS Panel",
		navSocialSyndication: "Social Syndication",
	},
	es: {
		loginHeading: "Acceder al panel de administración",
		loginDescription:
			"Utiliza una cuenta de administración autorizada para gestionar contenido, medios, redirecciones y publicación.",
		loginSubmit: "Iniciar sesión",
		loginEmailLabel: "Correo electrónico",
		loginPasswordLabel: "Contraseña",
		forgotPassword: "¿Olvidaste tu contraseña?",
		invalidCredentials: "El correo y la contraseña no se reconocen.",
		rateLimited: "Demasiados intentos. Espera un minuto e inténtalo de nuevo.",
		challengeRequired:
			"Completa el desafío de seguridad y vuelve a iniciar sesión.",
		passwordResetSuccess:
			"Tu contraseña se restableció correctamente. Inicia sesión con la nueva contraseña.",
		invitationAcceptedSuccess:
			"Tu invitación se aceptó correctamente. Inicia sesión con la nueva contraseña.",
		acceptInvitationHeading: "Aceptar invitación",
		acceptInvitationDescription:
			"Establece una contraseña para activar esta cuenta de administración invitada.",
		acceptInvitationSubmit: "Aceptar invitación",
		resetPasswordRequestHeading: "Restablecer contraseña",
		resetPasswordRequestDescription:
			"Introduce tu correo de administración y Astropress emitirá un enlace de restablecimiento si la cuenta existe.",
		resetPasswordTokenHeading: "Elige una nueva contraseña",
		resetPasswordTokenDescription:
			"Establece una nueva contraseña para esta cuenta de administración.",
		resetPasswordRequestSubmit: "Emitir enlace",
		resetPasswordTokenSubmit: "Guardar nueva contraseña",
		backToLogin: "Volver al inicio de sesión",
		themeToggleDark: "Cambiar a modo oscuro",
		themeToggleLight: "Cambiar a modo claro",
		signOut: "Cerrar sesión",
		signedInAsPrefix: "Sesión iniciada como",
		sidebarTitle: "Espacio de trabajo",
		navDashboard: "Panel",
		navContentGroup: "Contenido",
		navPosts: "Entradas",
		navPages: "Páginas",
		navMedia: "Medios",
		navComments: "Comentarios",
		navAuthors: "Autores",
		navTaxonomies: "Categorías y etiquetas",
		navRoutePages: "Tabla de rutas",
		navArchives: "Archivos",
		navRedirects: "Redirecciones",
		navTranslations: "Traducciones",
		navSeo: "SEO",
		navAccess: "Acceso",
		navUsers: "Usuarios",
		navSettings: "Configuración",
		navSystem: "Sistema",
		navApiTokens: "Tokens de API",
		navWebhooks: "Webhooks",
		navServices: "Servicios",
		navFundraising: "Recaudación",
		navTestimonials: "Testimonios",
		navCms: "CMS",
		navHost: "Hospedaje",
		navGroupSite: "Sitio",
		navGroupAudience: "Audiencia",
		navGroupComingSoon: "Próximamente",
		navGroupAccess: "Acceso",
		navForms: "Formularios",
		navSubscribers: "Suscriptores",
		navNewsletter: "Boletín",
		navEvents: "Eventos",
		navReviews: "Reseñas",
		navReferrals: "Referidos",
		navMemberships: "Membresías",
		navCommunity: "Comunidad",
		navShop: "Tienda",
		navStructuredData: "Datos estructurados / AEO",
		navSitemaps: "Mapas del sitio",
		navMapsLocal: "Mapas y local",
		navAnalytics: "Analítica",
		navHeatmaps: "Mapas de calor y repetición",
		navAbTesting: "Pruebas A/B y banderas",
		navEmail: "Correo",
		navLiveChat: "Chat en vivo",
		navImageCdn: "CDN de imágenes",
		navSearch: "Búsqueda",
		navCdnPurge: "Purga de CDN",
		navMonitoring: "Monitorización",
		navDeployHooks: "Hooks de despliegue",
		navPlugins: "Complementos",
		navData: "Datos",
		navBackups: "Copias de seguridad",
		stubNotConfiguredHeading: "Aún no configurado",
		stubHowToEnable: "Cómo activarlo",
		stubSupportedProviders: "Proveedores compatibles",
		stubLearnMore: "Más información",
		stubComingSoonHeading: "Próximamente",
		stubComingSoonBody:
			"Esta integración está en la hoja de ruta pero aún no está implementada.",
		stubComingSoonLink: "Sigue el progreso en GitHub",
		confirmDelete:
			"¿Seguro que quieres eliminar esto? Esta acción no se puede deshacer.",
		changeLanguage: "Cambiar idioma",
		approveComment: "Aprobar",
		cancelButton: "Cancelar",
		createPost: "Nueva entrada",
		deleteButton: "Eliminar",
		errorLabel: "Se produjo un error",
		loadingLabel: "Cargando…",
		publishButton: "Publicar",
		saveButton: "Guardar",
		navGroupDiscoverability: "Visibilidad",
		navGroupIntegrations: "Integraciones",
		navGroupOperations: "Operaciones",
		navHeadlessCmsPanel: "Panel CMS Headless",
		navSocialSyndication: "Sindicación social",
	},
	fr: {
		loginHeading: "Se connecter à l'administration",
		loginDescription:
			"Utilisez un compte administrateur autorisé pour gérer le contenu, les médias, les redirections et la publication.",
		loginSubmit: "Se connecter",
		loginEmailLabel: "Adresse e-mail",
		loginPasswordLabel: "Mot de passe",
		forgotPassword: "Mot de passe oublié ?",
		invalidCredentials: "Adresse e-mail ou mot de passe non reconnu.",
		rateLimited: "Trop de tentatives. Attendez une minute et réessayez.",
		challengeRequired:
			"Complétez la vérification de sécurité puis reconnectez-vous.",
		passwordResetSuccess:
			"Mot de passe réinitialisé. Connectez-vous avec le nouveau mot de passe.",
		invitationAcceptedSuccess:
			"Invitation acceptée. Connectez-vous avec le nouveau mot de passe.",
		acceptInvitationHeading: "Accepter l'invitation",
		acceptInvitationDescription:
			"Définissez un mot de passe pour activer ce compte administrateur invité.",
		acceptInvitationSubmit: "Accepter l'invitation",
		resetPasswordRequestHeading: "Réinitialiser le mot de passe",
		resetPasswordRequestDescription:
			"Saisissez votre adresse e-mail administrateur ; Astropress enverra un lien de réinitialisation si le compte existe.",
		resetPasswordTokenHeading: "Choisir un nouveau mot de passe",
		resetPasswordTokenDescription:
			"Définissez un nouveau mot de passe pour ce compte administrateur.",
		resetPasswordRequestSubmit: "Envoyer le lien",
		resetPasswordTokenSubmit: "Enregistrer le mot de passe",
		backToLogin: "Retour à la connexion",
		themeToggleDark: "Passer en mode sombre",
		themeToggleLight: "Passer en mode clair",
		signOut: "Se déconnecter",
		signedInAsPrefix: "Connecté en tant que",
		sidebarTitle: "Espace de travail",
		navDashboard: "Tableau de bord",
		navContentGroup: "Contenu",
		navPosts: "Articles",
		navPages: "Pages",
		navMedia: "Médias",
		navComments: "Commentaires",
		navAuthors: "Auteurs",
		navTaxonomies: "Catégories et étiquettes",
		navRoutePages: "Table des routes",
		navArchives: "Archives",
		navRedirects: "Redirections",
		navTranslations: "Traductions",
		navAccess: "Accès",
		navSeo: "SEO",
		navUsers: "Utilisateurs",
		navSettings: "Paramètres",
		navSystem: "Système",
		navApiTokens: "Jetons API",
		navWebhooks: "Webhooks",
		navServices: "Services",
		navFundraising: "Collecte de fonds",
		navTestimonials: "Témoignages",
		navCms: "CMS",
		navHost: "Hébergement",
		navGroupSite: "Site",
		navGroupAudience: "Audience",
		navGroupComingSoon: "Bientôt disponible",
		navGroupAccess: "Accès",
		navForms: "Formulaires",
		navSubscribers: "Abonnés",
		navNewsletter: "Newsletter",
		navEvents: "Événements",
		navReviews: "Avis",
		navReferrals: "Parrainages",
		navMemberships: "Abonnements",
		navCommunity: "Communauté",
		navShop: "Boutique",
		navStructuredData: "Données structurées / AEO",
		navSitemaps: "Plans du site",
		navMapsLocal: "Cartes et local",
		navAnalytics: "Analytique",
		navHeatmaps: "Cartes de chaleur",
		navAbTesting: "Tests A/B et drapeaux",
		navEmail: "E-mail",
		navLiveChat: "Chat en direct",
		navImageCdn: "CDN d'images",
		navSearch: "Recherche",
		navCdnPurge: "Purge CDN",
		navMonitoring: "Surveillance",
		navDeployHooks: "Hooks de déploiement",
		navPlugins: "Plugins",
		navData: "Données",
		navBackups: "Sauvegardes",
		stubNotConfiguredHeading: "Pas encore configuré",
		stubHowToEnable: "Comment l'activer",
		stubSupportedProviders: "Fournisseurs pris en charge",
		stubLearnMore: "En savoir plus",
		stubComingSoonHeading: "Bientôt disponible",
		stubComingSoonBody:
			"Cette intégration est sur la feuille de route mais n'est pas encore implémentée.",
		stubComingSoonLink: "Suivre l'avancement sur GitHub",
		confirmDelete:
			"Voulez-vous vraiment supprimer ceci ? Cette action est irréversible.",
		changeLanguage: "Changer de langue",
		approveComment: "Approuver",
		cancelButton: "Annuler",
		createPost: "Nouvel article",
		deleteButton: "Supprimer",
		errorLabel: "Une erreur est survenue",
		loadingLabel: "Chargement…",
		publishButton: "Publier",
		saveButton: "Enregistrer",
		navGroupDiscoverability: "Visibilité",
		navGroupIntegrations: "Intégrations",
		navGroupOperations: "Opérations",
		navHeadlessCmsPanel: "Panneau CMS Headless",
		navSocialSyndication: "Syndication sociale",
	},
	de: {
		loginHeading: "Beim Admin anmelden",
		loginDescription:
			"Verwenden Sie ein freigegebenes Admin-Konto, um Inhalte, Medien, Weiterleitungen und Veröffentlichungen zu verwalten.",
		loginSubmit: "Anmelden",
		loginEmailLabel: "E-Mail-Adresse",
		loginPasswordLabel: "Passwort",
		forgotPassword: "Passwort vergessen?",
		invalidCredentials: "E-Mail und Passwort wurden nicht erkannt.",
		rateLimited:
			"Zu viele Anmeldeversuche. Warten Sie eine Minute und versuchen Sie es erneut.",
		challengeRequired:
			"Schließen Sie die Sicherheitsprüfung ab und melden Sie sich erneut an.",
		passwordResetSuccess:
			"Ihr Passwort wurde erfolgreich zurückgesetzt. Melden Sie sich mit dem neuen Passwort an.",
		invitationAcceptedSuccess:
			"Ihre Einladung wurde erfolgreich angenommen. Melden Sie sich mit dem neuen Passwort an.",
		acceptInvitationHeading: "Einladung annehmen",
		acceptInvitationDescription:
			"Legen Sie ein Passwort fest, um dieses eingeladene Admin-Konto zu aktivieren.",
		acceptInvitationSubmit: "Einladung annehmen",
		resetPasswordRequestHeading: "Passwort zurücksetzen",
		resetPasswordRequestDescription:
			"Geben Sie Ihre Admin-E-Mail-Adresse ein. Astropress sendet einen Reset-Link, falls das Konto existiert.",
		resetPasswordTokenHeading: "Neues Passwort wählen",
		resetPasswordTokenDescription:
			"Legen Sie ein neues Passwort für dieses Admin-Konto fest.",
		resetPasswordRequestSubmit: "Link senden",
		resetPasswordTokenSubmit: "Passwort speichern",
		backToLogin: "Zurück zur Anmeldung",
		themeToggleDark: "Zum Dunkelmodus wechseln",
		themeToggleLight: "Zum Hellmodus wechseln",
		signOut: "Abmelden",
		signedInAsPrefix: "Angemeldet als",
		sidebarTitle: "Arbeitsbereich",
		navDashboard: "Dashboard",
		navContentGroup: "Inhalt",
		navPosts: "Beiträge",
		navPages: "Seiten",
		navMedia: "Medien",
		navComments: "Kommentare",
		navAuthors: "Autoren",
		navTaxonomies: "Kategorien & Tags",
		navRoutePages: "Routentabelle",
		navArchives: "Archive",
		navRedirects: "Weiterleitungen",
		navAccess: "Zugriff",
		navTranslations: "Übersetzungen",
		navSeo: "SEO",
		navUsers: "Benutzer",
		navSettings: "Einstellungen",
		navSystem: "System",
		navApiTokens: "API-Token",
		navWebhooks: "Webhooks",
		navServices: "Dienste",
		navFundraising: "Spendenaktionen",
		navTestimonials: "Stimmen",
		navCms: "CMS",
		navHost: "Hosting",
		navGroupSite: "Website",
		navGroupAudience: "Zielgruppe",
		navGroupComingSoon: "Demnächst",
		navGroupAccess: "Zugriff",
		navForms: "Formulare",
		navSubscribers: "Abonnenten",
		navNewsletter: "Newsletter",
		navEvents: "Veranstaltungen",
		navReviews: "Bewertungen",
		navReferrals: "Empfehlungen",
		navMemberships: "Mitgliedschaften",
		navCommunity: "Community",
		navShop: "Shop",
		navStructuredData: "Strukturierte Daten / AEO",
		navSitemaps: "Sitemaps",
		navMapsLocal: "Karten & Lokal",
		navAnalytics: "Analytik",
		navHeatmaps: "Heatmaps & Session-Replay",
		navAbTesting: "A/B-Tests & Feature-Flags",
		navEmail: "E-Mail",
		navLiveChat: "Live-Chat",
		navImageCdn: "Bild-CDN",
		navSearch: "Suche",
		navCdnPurge: "CDN-Purge",
		navMonitoring: "Überwachung",
		navDeployHooks: "Deploy-Hooks",
		navPlugins: "Plugins",
		navData: "Daten",
		navBackups: "Backups",
		stubNotConfiguredHeading: "Noch nicht konfiguriert",
		stubHowToEnable: "So aktivieren Sie es",
		stubSupportedProviders: "Unterstützte Anbieter",
		stubLearnMore: "Mehr erfahren",
		stubComingSoonHeading: "Demnächst",
		stubComingSoonBody:
			"Diese Integration steht auf der Roadmap, ist aber noch nicht implementiert.",
		stubComingSoonLink: "Fortschritt auf GitHub verfolgen",
		confirmDelete:
			"Möchten Sie dies wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
		changeLanguage: "Sprache ändern",
		approveComment: "Genehmigen",
		cancelButton: "Abbrechen",
		createPost: "Neuer Beitrag",
		deleteButton: "Löschen",
		errorLabel: "Ein Fehler ist aufgetreten",
		loadingLabel: "Wird geladen…",
		publishButton: "Veröffentlichen",
		saveButton: "Speichern",
		navGroupDiscoverability: "Auffindbarkeit",
		navGroupIntegrations: "Integrationen",
		navGroupOperations: "Betrieb",
		navHeadlessCmsPanel: "Headless-CMS-Panel",
		navSocialSyndication: "Social-Syndication",
	},
	pt: {
		loginHeading: "Entrar no painel de administração",
		loginDescription:
			"Use uma conta de administração autorizada para gerenciar conteúdo, mídia, redirecionamentos e publicação.",
		loginSubmit: "Entrar",
		loginEmailLabel: "Endereço de e-mail",
		loginPasswordLabel: "Senha",
		forgotPassword: "Esqueceu sua senha?",
		invalidCredentials: "E-mail e senha não reconhecidos.",
		rateLimited: "Muitas tentativas. Aguarde um minuto e tente novamente.",
		challengeRequired:
			"Conclua o desafio de segurança e tente entrar novamente.",
		passwordResetSuccess: "Sua senha foi redefinida. Entre com a nova senha.",
		invitationAcceptedSuccess: "Convite aceito. Entre com a nova senha.",
		acceptInvitationHeading: "Aceitar convite",
		acceptInvitationDescription:
			"Defina uma senha para ativar esta conta de administração convidada.",
		acceptInvitationSubmit: "Aceitar convite",
		resetPasswordRequestHeading: "Redefinir senha",
		resetPasswordRequestDescription:
			"Digite seu e-mail de administração; Astropress enviará um link de redefinição se a conta existir.",
		resetPasswordTokenHeading: "Escolher nova senha",
		resetPasswordTokenDescription:
			"Defina uma nova senha para esta conta de administração.",
		resetPasswordRequestSubmit: "Enviar link",
		resetPasswordTokenSubmit: "Salvar nova senha",
		backToLogin: "Voltar ao login",
		themeToggleDark: "Mudar para modo escuro",
		themeToggleLight: "Mudar para modo claro",
		signOut: "Sair",
		signedInAsPrefix: "Conectado como",
		sidebarTitle: "Área de trabalho",
		navDashboard: "Painel",
		navContentGroup: "Conteúdo",
		navPosts: "Publicações",
		navPages: "Páginas",
		navMedia: "Mídia",
		navComments: "Comentários",
		navAuthors: "Autores",
		navTaxonomies: "Categorias e tags",
		navRoutePages: "Tabela de rotas",
		navArchives: "Arquivos",
		navAccess: "Acesso",
		navRedirects: "Redirecionamentos",
		navTranslations: "Traduções",
		navSeo: "SEO",
		navUsers: "Usuários",
		navSettings: "Configurações",
		navSystem: "Sistema",
		navApiTokens: "Tokens de API",
		navWebhooks: "Webhooks",
		navServices: "Serviços",
		navFundraising: "Arrecadação",
		navTestimonials: "Depoimentos",
		navCms: "CMS",
		navHost: "Hospedagem",
		navGroupSite: "Site",
		navGroupAudience: "Público",
		navGroupComingSoon: "Em breve",
		navGroupAccess: "Acesso",
		navForms: "Formulários",
		navSubscribers: "Assinantes",
		navNewsletter: "Newsletter",
		navEvents: "Eventos",
		navReviews: "Avaliações",
		navReferrals: "Indicações",
		navMemberships: "Associações",
		navCommunity: "Comunidade",
		navShop: "Loja",
		navStructuredData: "Dados estruturados / AEO",
		navSitemaps: "Sitemaps",
		navMapsLocal: "Mapas e local",
		navAnalytics: "Análise",
		navHeatmaps: "Mapas de calor e replay",
		navAbTesting: "Testes A/B e flags",
		navEmail: "Email",
		navLiveChat: "Chat ao vivo",
		navImageCdn: "CDN de imagens",
		navSearch: "Busca",
		navCdnPurge: "Purgar CDN",
		navMonitoring: "Monitoramento",
		navDeployHooks: "Hooks de implantação",
		navPlugins: "Plugins",
		navData: "Dados",
		navBackups: "Backups",
		stubNotConfiguredHeading: "Ainda não configurado",
		stubHowToEnable: "Como ativar",
		stubSupportedProviders: "Provedores suportados",
		stubLearnMore: "Saiba mais",
		stubComingSoonHeading: "Em breve",
		stubComingSoonBody:
			"Esta integração está no roadmap, mas ainda não foi implementada.",
		stubComingSoonLink: "Acompanhe o progresso no GitHub",
		confirmDelete:
			"Tem certeza que quer excluir isso? Esta ação não pode ser desfeita.",
		changeLanguage: "Alterar idioma",
		approveComment: "Aprovar",
		cancelButton: "Cancelar",
		createPost: "Nova publicação",
		deleteButton: "Excluir",
		errorLabel: "Ocorreu um erro",
		loadingLabel: "Carregando…",
		publishButton: "Publicar",
		saveButton: "Salvar",
		navGroupDiscoverability: "Descoberta",
		navGroupIntegrations: "Integrações",
		navGroupOperations: "Operações",
		navHeadlessCmsPanel: "Painel CMS Headless",
		navSocialSyndication: "Sindicação social",
	},
	ja: {
		loginHeading: "管理パネルにサインイン",
		loginDescription:
			"承認された管理アカウントでコンテンツ、メディア、リダイレクト、公開設定を管理してください。",
		loginSubmit: "サインイン",
		loginEmailLabel: "メールアドレス",
		loginPasswordLabel: "パスワード",
		forgotPassword: "パスワードをお忘れですか？",
		invalidCredentials:
			"メールアドレスとパスワードの組み合わせが正しくありません。",
		rateLimited:
			"サインインの試行回数が多すぎます。1分待って再度お試しください。",
		challengeRequired:
			"セキュリティチェックを完了してから再度サインインしてください。",
		passwordResetSuccess:
			"パスワードがリセットされました。新しいパスワードでサインインしてください。",
		invitationAcceptedSuccess:
			"招待が承認されました。新しいパスワードでサインインしてください。",
		acceptInvitationHeading: "招待を承認",
		acceptInvitationDescription:
			"パスワードを設定して、招待された管理アカウントを有効化します。",
		acceptInvitationSubmit: "招待を承認",
		resetPasswordRequestHeading: "パスワードのリセット",
		resetPasswordRequestDescription:
			"管理者のメールアドレスを入力してください。アカウントが存在する場合、Astropress がリセットリンクを送信します。",
		resetPasswordTokenHeading: "新しいパスワードを選択",
		resetPasswordTokenDescription:
			"この管理アカウントの新しいパスワードを設定します。",
		resetPasswordRequestSubmit: "リンクを送信",
		resetPasswordTokenSubmit: "新しいパスワードを保存",
		backToLogin: "ログインに戻る",
		themeToggleDark: "ダークモードに切り替え",
		themeToggleLight: "ライトモードに切り替え",
		signOut: "サインアウト",
		signedInAsPrefix: "サインイン中:",
		sidebarTitle: "ワークスペース",
		navDashboard: "ダッシュボード",
		navContentGroup: "コンテンツ",
		navPosts: "投稿",
		navPages: "ページ",
		navMedia: "メディア",
		navComments: "コメント",
		navAuthors: "著者",
		navTaxonomies: "カテゴリとタグ",
		navRoutePages: "ルートテーブル",
		navAccess: "アクセス",
		navArchives: "アーカイブ",
		navRedirects: "リダイレクト",
		navTranslations: "翻訳",
		navSeo: "SEO",
		navUsers: "ユーザー",
		navSettings: "設定",
		navSystem: "システム",
		navApiTokens: "APIトークン",
		navWebhooks: "Webhook",
		navServices: "サービス",
		navFundraising: "募金",
		navTestimonials: "推薦の声",
		navCms: "CMS",
		navHost: "ホスティング",
		navGroupSite: "サイト",
		navGroupAudience: "オーディエンス",
		navGroupComingSoon: "近日公開",
		navGroupAccess: "アクセス",
		navForms: "フォーム",
		navSubscribers: "購読者",
		navNewsletter: "ニュースレター",
		navEvents: "イベント",
		navReviews: "レビュー",
		navReferrals: "紹介",
		navMemberships: "メンバーシップ",
		navCommunity: "コミュニティ",
		navShop: "ショップ",
		navStructuredData: "構造化データ / AEO",
		navSitemaps: "サイトマップ",
		navMapsLocal: "マップとローカル",
		navAnalytics: "分析",
		navHeatmaps: "ヒートマップとセッション再生",
		navAbTesting: "A/Bテストとフラグ",
		navEmail: "メール",
		navLiveChat: "ライブチャット",
		navImageCdn: "画像CDN",
		navSearch: "検索",
		navCdnPurge: "CDNパージ",
		navMonitoring: "モニタリング",
		navDeployHooks: "デプロイフック",
		navPlugins: "プラグイン",
		navData: "データ",
		navBackups: "バックアップ",
		stubNotConfiguredHeading: "未設定",
		stubHowToEnable: "有効化する方法",
		stubSupportedProviders: "対応プロバイダー",
		stubLearnMore: "詳しく見る",
		stubComingSoonHeading: "近日公開",
		stubComingSoonBody:
			"この連携はロードマップに含まれていますが、まだ実装されていません。",
		stubComingSoonLink: "GitHub で進捗を確認",
		changeLanguage: "言語を変更",
		approveComment: "承認",
		cancelButton: "キャンセル",
		confirmDelete: "本当に削除しますか？この操作は元に戻せません。",
		createPost: "新しい投稿",
		deleteButton: "削除",
		errorLabel: "エラーが発生しました",
		loadingLabel: "読み込み中…",
		publishButton: "公開",
		saveButton: "保存",
		navGroupDiscoverability: "発見性",
		navGroupIntegrations: "連携",
		navGroupOperations: "運用",
		navHeadlessCmsPanel: "ヘッドレスCMSパネル",
		navSocialSyndication: "ソーシャル配信",
	},
	te: {
		loginHeading: "అడ్మిన్‌లోకి సైన్ ఇన్ చేయండి",
		loginDescription:
			"కంటెంట్, మీడియా, రీడైరెక్ట్‌లు, ప్రచురణ సెట్టింగ్‌లను నిర్వహించడానికి ఆమోదిత అడ్మిన్ ఖాతాను ఉపయోగించండి.",
		loginSubmit: "సైన్ ఇన్",
		loginEmailLabel: "ఇమెయిల్ చిరునామా",
		loginPasswordLabel: "పాస్‌వర్డ్",
		forgotPassword: "పాస్‌వర్డ్ మర్చిపోయారా?",
		invalidCredentials: "ఆ ఇమెయిల్, పాస్‌వర్డ్ కలయిక గుర్తించబడలేదు.",
		rateLimited: "చాలా సైన్-ఇన్ ప్రయత్నాలు. ఒక నిమిషం వేచి మళ్ళీ ప్రయత్నించండి.",
		challengeRequired: "భద్రతా సవాల్‌ని పూర్తి చేసి మళ్ళీ సైన్ ఇన్ ప్రయత్నించండి.",
		passwordResetSuccess: "మీ పాస్‌వర్డ్ విజయవంతంగా రీసెట్ చేయబడింది. కొత్త పాస్‌వర్డ్‌తో సైన్ ఇన్ చేయండి.",
		invitationAcceptedSuccess:
			"మీ ఆహ్వానం విజయవంతంగా ఆమోదించబడింది. కొత్త పాస్‌వర్డ్‌తో సైన్ ఇన్ చేయండి.",
		acceptInvitationHeading: "ఆహ్వానాన్ని ఆమోదించండి",
		acceptInvitationDescription: "ఈ ఆహ్వానిత అడ్మిన్ ఖాతాను సక్రియం చేయడానికి పాస్‌వర్డ్ సెట్ చేయండి.",
		acceptInvitationSubmit: "ఆహ్వానాన్ని ఆమోదించండి",
		resetPasswordRequestHeading: "పాస్‌వర్డ్ రీసెట్",
		resetPasswordRequestDescription:
			"మీ అడ్మిన్ ఇమెయిల్ చిరునామాను నమోదు చేయండి; ఖాతా ఉన్నట్లయితే Astropress రీసెట్ లింక్‌ను పంపుతుంది.",
		resetPasswordTokenHeading: "కొత్త పాస్‌వర్డ్ ఎంచుకోండి",
		resetPasswordTokenDescription: "ఈ అడ్మిన్ ఖాతాకు కొత్త పాస్‌వర్డ్ సెట్ చేయండి.",
		resetPasswordRequestSubmit: "లింక్ పంపండి",
		resetPasswordTokenSubmit: "కొత్త పాస్‌వర్డ్ సేవ్ చేయండి",
		backToLogin: "లాగిన్‌కి తిరిగి",
		themeToggleDark: "డార్క్ మోడ్‌కి మారండి",
		themeToggleLight: "లైట్ మోడ్‌కి మారండి",
		signOut: "సైన్ అవుట్",
		signedInAsPrefix: "సైన్ ఇన్:",
		sidebarTitle: "వర్క్‌స్పేస్",
		navDashboard: "డాష్‌బోర్డ్",
		navContentGroup: "కంటెంట్",
		navPosts: "పోస్ట్‌లు",
		navPages: "పేజీలు",
		navMedia: "మీడియా",
		navComments: "వ్యాఖ్యలు",
		navAuthors: "రచయితలు",
		navTaxonomies: "వర్గాలు & ట్యాగ్‌లు",
		navAccess: "యాక్సెస్",
		navRoutePages: "రూట్ పట్టిక",
		navArchives: "ఆర్కైవ్‌లు",
		navRedirects: "రీడైరెక్ట్‌లు",
		navTranslations: "అనువాదాలు",
		navSeo: "ఎస్‌ఈఓ",
		navUsers: "వినియోగదారులు",
		navSettings: "సెట్టింగ్‌లు",
		navSystem: "సిస్టమ్",
		navApiTokens: "API టోకెన్‌లు",
		navWebhooks: "వెబ్‌హుక్‌లు",
		navServices: "సేవలు",
		navFundraising: "విరాళ సేకరణ",
		navTestimonials: "ప్రశంసలు",
		navCms: "CMS",
		navHost: "హోస్టింగ్",
		navGroupSite: "సైట్",
		navGroupAudience: "ప్రేక్షకులు",
		navGroupComingSoon: "త్వరలో",
		navGroupAccess: "యాక్సెస్",
		navForms: "ఫారాలు",
		navSubscribers: "చందాదారులు",
		navNewsletter: "న్యూస్‌లెటర్",
		navEvents: "ఈవెంట్‌లు",
		navReviews: "సమీక్షలు",
		navReferrals: "రెఫరల్స్",
		navMemberships: "సభ్యత్వాలు",
		navCommunity: "సముదాయం",
		navShop: "షాప్",
		navStructuredData: "నిర్మిత డేటా / AEO",
		navSitemaps: "సైట్‌మ్యాప్‌లు",
		navMapsLocal: "మ్యాప్‌లు & స్థానిక",
		navAnalytics: "విశ్లేషణలు",
		navHeatmaps: "హీట్‌మ్యాప్‌లు",
		navAbTesting: "A/B పరీక్ష",
		navEmail: "ఇమెయిల్",
		navLiveChat: "లైవ్ చాట్",
		navImageCdn: "ఇమేజ్ CDN",
		navSearch: "వెతుకు",
		navCdnPurge: "CDN ప్యూర్జ్",
		navMonitoring: "మానిటరింగ్",
		navDeployHooks: "డిప్లాయ్ హుక్‌లు",
		navPlugins: "ప్లగిన్‌లు",
		navData: "డేటా",
		navBackups: "బ్యాకప్‌లు",
		stubNotConfiguredHeading: "ఇంకా కాన్ఫిగర్ చేయబడలేదు",
		stubHowToEnable: "ఎలా ప్రారంభించాలి",
		stubSupportedProviders: "మద్దతు ఉన్న ప్రొవైడర్లు",
		stubLearnMore: "మరింత తెలుసుకోండి",
		stubComingSoonHeading: "త్వరలో",
		stubComingSoonBody: "ఈ ఏకీకరణ రోడ్‌మ్యాప్‌లో ఉంది, కానీ ఇంకా అమలు చేయబడలేదు.",
		stubComingSoonLink: "GitHub లో ప్రోగ్రెస్‌ని ట్రాక్ చేయండి",
		changeLanguage: "భాష మార్చండి",
		approveComment: "ఆమోదించండి",
		cancelButton: "రద్దు",
		confirmDelete: "దీన్ని తొలగించాలనుకుంటున్నారా? ఈ చర్యను రద్దు చేయలేరు.",
		createPost: "కొత్త పోస్ట్",
		deleteButton: "తొలగించండి",
		errorLabel: "చర్య విఫలమైంది",
		loadingLabel: "లోడ్ అవుతోంది…",
		publishButton: "ప్రచురించండి",
		saveButton: "సేవ్",
		navGroupDiscoverability: "కనుగొనదగినత",
		navGroupIntegrations: "అనుసంధానాలు",
		navGroupOperations: "ఆపరేషన్లు",
		navHeadlessCmsPanel: "హెడ్‌లెస్ CMS ప్యానెల్",
		navSocialSyndication: "సోషల్ సిండికేషన్",
	},
	hi: {
		loginHeading: "एडमिन में साइन इन करें",
		loginDescription:
			"सामग्री, मीडिया, रीडायरेक्ट और प्रकाशन सेटिंग्स प्रबंधित करने के लिए स्वीकृत एडमिन खाते का उपयोग करें.",
		loginSubmit: "साइन इन",
		loginEmailLabel: "ईमेल पता",
		loginPasswordLabel: "पासवर्ड",
		forgotPassword: "पासवर्ड भूल गए?",
		invalidCredentials: "वह ईमेल और पासवर्ड संयोजन पहचाना नहीं गया.",
		rateLimited: "बहुत अधिक प्रयास. एक मिनट प्रतीक्षा करें और फिर से प्रयास करें.",
		challengeRequired: "सुरक्षा चुनौती पूरी करें और दोबारा साइन इन करें.",
		passwordResetSuccess:
			"आपका पासवर्ड सफलतापूर्वक रीसेट हो गया. नए पासवर्ड से साइन इन करें.",
		invitationAcceptedSuccess:
			"आपका निमंत्रण स्वीकार किया गया. नए पासवर्ड से साइन इन करें.",
		acceptInvitationHeading: "निमंत्रण स्वीकार करें",
		acceptInvitationDescription:
			"इस आमंत्रित एडमिन खाते को सक्रिय करने के लिए पासवर्ड सेट करें.",
		acceptInvitationSubmit: "निमंत्रण स्वीकार करें",
		resetPasswordRequestHeading: "पासवर्ड रीसेट",
		resetPasswordRequestDescription:
			"अपना एडमिन ईमेल पता दर्ज करें; खाता मौजूद होने पर Astropress रीसेट लिंक भेजेगा.",
		resetPasswordTokenHeading: "नया पासवर्ड चुनें",
		resetPasswordTokenDescription: "इस एडमिन खाते के लिए नया पासवर्ड सेट करें.",
		resetPasswordRequestSubmit: "लिंक भेजें",
		resetPasswordTokenSubmit: "नया पासवर्ड सहेजें",
		backToLogin: "लॉगिन पर वापस",
		themeToggleDark: "डार्क मोड पर स्विच करें",
		themeToggleLight: "लाइट मोड पर स्विच करें",
		signOut: "साइन आउट",
		signedInAsPrefix: "साइन इन के रूप में:",
		sidebarTitle: "वर्कस्पेस",
		navDashboard: "डैशबोर्ड",
		navContentGroup: "सामग्री",
		navPosts: "पोस्ट",
		navPages: "पृष्ठ",
		navMedia: "मीडिया",
		navComments: "टिप्पणियाँ",
		navAuthors: "लेखक",
		navAccess: "एक्सेस",
		navTaxonomies: "श्रेणियाँ और टैग",
		navRoutePages: "रूट तालिका",
		navArchives: "अभिलेख",
		navRedirects: "रीडायरेक्ट",
		navTranslations: "अनुवाद",
		navSeo: "एसईओ",
		navUsers: "उपयोगकर्ता",
		navSettings: "सेटिंग्स",
		navSystem: "सिस्टम",
		navApiTokens: "API टोकन",
		navWebhooks: "Webhooks",
		navServices: "सेवाएँ",
		navFundraising: "धन उगाही",
		navTestimonials: "प्रशंसापत्र",
		navCms: "CMS",
		navHost: "होस्टिंग",
		navGroupSite: "साइट",
		navGroupAudience: "ऑडियंस",
		navGroupComingSoon: "जल्द आ रहा है",
		navGroupAccess: "पहुँच",
		navForms: "फ़ॉर्म",
		navSubscribers: "ग्राहक",
		navNewsletter: "न्यूज़लेटर",
		navEvents: "इवेंट",
		navReviews: "समीक्षा",
		navReferrals: "रेफ़रल",
		navMemberships: "मेम्बरशिप",
		navCommunity: "समुदाय",
		navShop: "दुकान",
		navStructuredData: "संरचित डेटा / AEO",
		navSitemaps: "साइटमैप",
		navMapsLocal: "मानचित्र और स्थानीय",
		navAnalytics: "एनालिटिक्स",
		navHeatmaps: "हीटमैप",
		navAbTesting: "A/B परीक्षण",
		navEmail: "ईमेल",
		navLiveChat: "लाइव चैट",
		navImageCdn: "इमेज CDN",
		navSearch: "खोज",
		navCdnPurge: "CDN पर्ज",
		navMonitoring: "निगरानी",
		navDeployHooks: "डिप्लॉय हुक",
		navPlugins: "प्लगइन",
		navData: "डेटा",
		navBackups: "बैकअप",
		stubNotConfiguredHeading: "अभी कॉन्फ़िगर नहीं हुआ",
		stubHowToEnable: "इसे कैसे सक्षम करें",
		stubSupportedProviders: "समर्थित प्रदाता",
		stubLearnMore: "और जानें",
		stubComingSoonHeading: "जल्द आ रहा है",
		stubComingSoonBody: "यह इंटीग्रेशन रोडमैप में है लेकिन अभी तक लागू नहीं किया गया है।",
		stubComingSoonLink: "GitHub पर प्रगति देखें",
		confirmDelete:
			"क्या आप वाकई इसे मिटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती.",
		changeLanguage: "भाषा बदलें",
		approveComment: "स्वीकृत करें",
		cancelButton: "रद्द करें",
		createPost: "नई पोस्ट",
		deleteButton: "मिटाएँ",
		errorLabel: "क्रिया विफल",
		loadingLabel: "लोड हो रहा है…",
		publishButton: "प्रकाशित करें",
		saveButton: "सहेजें",
		navGroupDiscoverability: "खोज-योग्यता",
		navGroupIntegrations: "इंटीग्रेशन",
		navGroupOperations: "संचालन",
		navHeadlessCmsPanel: "हेडलेस CMS पैनल",
		navSocialSyndication: "सोशल सिंडिकेशन",
	},
	ny: {
		loginHeading: "Lowani mu admin",
		loginDescription:
			"Gwiritsani ntchito akaunti yovomerezeka kuti muyendetse zinthu, ma media, ma redirect, ndi zofalitsa.",
		loginSubmit: "Lowani",
		loginEmailLabel: "Imelo",
		loginPasswordLabel: "Mawu achinsinsi",
		forgotPassword: "Mwaiwala mawu achinsinsi?",
		invalidCredentials: "Imelo ndi mawu achinsinsi sizinazindikiridwe.",
		rateLimited: "Kuyesayesa kochuluka. Dikirani mphindi imodzi ndikuyesa.",
		challengeRequired: "Malizani chitetezo ndi kulowanso.",
		passwordResetSuccess:
			"Mawu achinsinsi anu asinthidwa. Lowani ndi mawu atsopano.",
		invitationAcceptedSuccess:
			"Pempho lanu lalandiridwa. Lowani ndi mawu atsopano.",
		acceptInvitationHeading: "Landirani pempho",
		acceptInvitationDescription:
			"Ikani mawu achinsinsi kuti muyatsanitse akaunti yoyitanidwa.",
		acceptInvitationSubmit: "Landirani pempho",
		resetPasswordRequestHeading: "Sinthani mawu achinsinsi",
		resetPasswordRequestDescription:
			"Lembani imelo yanu; Astropress idzatumiza ulalo wokongolanso ngati akaunti ilipo.",
		resetPasswordTokenHeading: "Sankhani mawu atsopano",
		resetPasswordTokenDescription:
			"Ikani mawu atsopano achinsinsi pa akaunti iyi.",
		resetPasswordRequestSubmit: "Tumizani ulalo",
		resetPasswordTokenSubmit: "Sungani mawu atsopano",
		backToLogin: "Bwerera ku login",
		themeToggleDark: "Sinthani ku mtundu wakuda",
		themeToggleLight: "Sinthani ku mtundu woyera",
		signOut: "Tulukani",
		signedInAsPrefix: "Walowa monga",
		sidebarTitle: "Malo ogwirira",
		navDashboard: "Dashboard",
		navContentGroup: "Zinthu",
		navPosts: "Maposiketi",
		navPages: "Masamba",
		navMedia: "Media",
		navComments: "Ndemanga",
		navAccess: "Mwayi",
		navAuthors: "Olemba",
		navTaxonomies: "Magulu ndi Ma tag",
		navRoutePages: "Tebulo la mizere",
		navArchives: "Zosungidwa",
		navRedirects: "Maredirect",
		navTranslations: "Matembenuzidwe",
		navSeo: "SEO",
		navUsers: "Ogwiritsa",
		navSettings: "Zokonzekera",
		navSystem: "Sisitimu",
		navApiTokens: "Matokeni a API",
		navWebhooks: "Webhooks",
		navServices: "Mautumiki",
		navFundraising: "Kusonkhanitsa ndalama",
		navTestimonials: "Maumboni",
		navCms: "CMS",
		navHost: "Ho hosting",
		navGroupSite: "Tsamba",
		navGroupAudience: "Omvera",
		navGroupComingSoon: "Posachedwapa",
		navGroupAccess: "Mwayi",
		navForms: "Mafomu",
		navSubscribers: "Olembetsa",
		navNewsletter: "Nkhani",
		navEvents: "Zochitika",
		navReviews: "Ndemanga",
		navReferrals: "Zonena",
		navMemberships: "Umembala",
		navCommunity: "Anthu",
		navShop: "Sitolo",
		navStructuredData: "Deta Yokonzedwa / AEO",
		navSitemaps: "Mamapu a Tsamba",
		navMapsLocal: "Mamapu ndi Komweko",
		navAnalytics: "Kusanthula",
		navHeatmaps: "Mamapu a Kutentha",
		navAbTesting: "Kuyesa A/B",
		navEmail: "Imelo",
		navLiveChat: "Kucheza Pa Live",
		navImageCdn: "CDN ya Zithunzi",
		navSearch: "Funafuna",
		navCdnPurge: "Kuyeretsa CDN",
		navMonitoring: "Kuyang'anira",
		navDeployHooks: "Ma hook a Kutumiza",
		navPlugins: "Ma plugin",
		navData: "Deta",
		navBackups: "Zosunga",
		stubNotConfiguredHeading: "Sichinakonzedwe pano",
		stubHowToEnable: "Momwe Mungayambitsire",
		stubSupportedProviders: "Operekera Othandizidwa",
		stubLearnMore: "Phunzirani Zambiri",
		stubComingSoonHeading: "Posachedwapa",
		stubComingSoonBody:
			"Kuphatikiza uku kuli pa mapu a tsogolo koma sikunakhazikitsidwebe.",
		stubComingSoonLink: "Tsatirani kupita patsogolo pa GitHub",
		confirmDelete:
			"Mukutsimikiza kuchotsa izi? Chochita ichi sichingathe kubwezedwa.",
		changeLanguage: "Sinthani chinenero",
		approveComment: "Vomerezani",
		cancelButton: "Letsani",
		createPost: "Positi yatsopano",
		deleteButton: "Chotsani",
		errorLabel: "Sichinatheke",
		loadingLabel: "Akutsegula…",
		publishButton: "Falitsani",
		saveButton: "Sungani",
		navGroupDiscoverability: "Kupezeka",
		navGroupIntegrations: "Kuphatikiza",
		navGroupOperations: "Ntchito",
		navHeadlessCmsPanel: "Gulu la CMS Lopanda Mutu",
		navSocialSyndication: "Kufalitsa Pa Social",
	},
	ar: {
		loginHeading: "تسجيل الدخول إلى لوحة الإدارة",
		loginDescription:
			"استخدم حساب إدارة معتمدًا لإدارة المحتوى والوسائط وعمليات إعادة التوجيه وإعدادات النشر.",
		loginSubmit: "تسجيل الدخول",
		loginEmailLabel: "البريد الإلكتروني",
		loginPasswordLabel: "كلمة المرور",
		forgotPassword: "هل نسيت كلمة المرور؟",
		invalidCredentials: "لم يتم التعرف على البريد الإلكتروني وكلمة المرور.",
		rateLimited:
			"تم تسجيل عدد كبير من محاولات الدخول. انتظر دقيقة وحاول مرة أخرى.",
		challengeRequired: "أكمل تحدي الأمان وحاول تسجيل الدخول مرة أخرى.",
		passwordResetSuccess:
			"تم إعادة تعيين كلمة المرور بنجاح. سجّل الدخول بكلمة المرور الجديدة.",
		invitationAcceptedSuccess:
			"تم قبول الدعوة بنجاح. سجّل الدخول بكلمة المرور الجديدة.",
		acceptInvitationHeading: "قبول الدعوة",
		acceptInvitationDescription: "حدد كلمة مرور لتفعيل حساب المسؤول المدعو.",
		acceptInvitationSubmit: "قبول الدعوة",
		resetPasswordRequestHeading: "إعادة تعيين كلمة المرور",
		resetPasswordRequestDescription:
			"أدخل بريدك الإلكتروني وستُرسل Astropress رابط إعادة التعيين إذا كان الحساب موجودًا.",
		resetPasswordTokenHeading: "اختر كلمة مرور جديدة",
		resetPasswordTokenDescription: "حدد كلمة مرور جديدة لهذا الحساب.",
		resetPasswordRequestSubmit: "إرسال رابط إعادة التعيين",
		resetPasswordTokenSubmit: "حفظ كلمة المرور الجديدة",
		backToLogin: "العودة إلى تسجيل الدخول",
		themeToggleDark: "التبديل إلى الوضع الداكن",
		themeToggleLight: "التبديل إلى الوضع الفاتح",
		signOut: "تسجيل الخروج",
		signedInAsPrefix: "تم تسجيل الدخول باسم",
		sidebarTitle: "مساحة العمل",
		navDashboard: "لوحة التحكم",
		navContentGroup: "المحتوى",
		navPosts: "المنشورات",
		navPages: "الصفحات",
		navMedia: "الوسائط",
		navComments: "التعليقات",
		navAuthors: "المؤلفون",
		navTaxonomies: "التصنيفات والوسوم",
		navRoutePages: "جدول المسارات",
		navArchives: "الأرشيف",
		navRedirects: "إعادة التوجيه",
		navTranslations: "الترجمات",
		navSeo: "تحسين محركات البحث",
		navUsers: "المستخدمون",
		navAccess: "الصلاحيات",
		navSettings: "الإعدادات",
		navSystem: "النظام",
		navApiTokens: "رموز واجهة البرمجة",
		navWebhooks: "الويب هوكس",
		navServices: "الخدمات",
		navFundraising: "جمع التبرعات",
		navTestimonials: "الشهادات",
		navCms: "نظام إدارة المحتوى",
		navHost: "المضيف",
		navGroupSite: "الموقع",
		navGroupAudience: "الجمهور",
		navGroupComingSoon: "قريبًا",
		navGroupAccess: "الصلاحيات",
		navForms: "النماذج",
		navSubscribers: "المشتركون",
		navNewsletter: "النشرة البريدية",
		navEvents: "الفعاليات",
		navReviews: "المراجعات",
		navReferrals: "الإحالات",
		navMemberships: "العضويات",
		navCommunity: "المجتمع",
		navShop: "المتجر",
		navStructuredData: "البيانات المنظمة / AEO",
		navSitemaps: "خرائط الموقع",
		navMapsLocal: "الخرائط والمحلي",
		navAnalytics: "التحليلات",
		navHeatmaps: "الخرائط الحرارية وإعادة الجلسة",
		navAbTesting: "اختبار A/B وعلامات الميزات",
		navEmail: "البريد الإلكتروني",
		navLiveChat: "الدردشة المباشرة",
		navImageCdn: "شبكة توصيل الصور",
		navSearch: "البحث",
		navCdnPurge: "تفريغ الذاكرة المؤقتة",
		navMonitoring: "المراقبة",
		navDeployHooks: "خطافات النشر",
		navPlugins: "الإضافات",
		navData: "البيانات",
		navBackups: "النسخ الاحتياطية",
		stubNotConfiguredHeading: "غير مُكوَّن بعد",
		stubHowToEnable: "كيفية التفعيل",
		stubSupportedProviders: "المزودون المدعومون",
		stubLearnMore: "اعرف المزيد",
		stubComingSoonHeading: "قريبًا",
		stubComingSoonBody: "هذا التكامل ضمن خارطة الطريق ولكنه لم يُنفَّذ بعد.",
		stubComingSoonLink: "تابع التقدّم على GitHub",
		changeLanguage: "تغيير اللغة",
		approveComment: "موافقة",
		cancelButton: "إلغاء",
		confirmDelete: "هل أنت متأكد من الحذف؟ لا يمكن التراجع عن هذا الإجراء.",
		createPost: "منشور جديد",
		deleteButton: "حذف",
		errorLabel: "فشل الإجراء",
		loadingLabel: "جارٍ التحميل…",
		publishButton: "نشر",
		saveButton: "حفظ",
		navGroupDiscoverability: "إمكانية الاكتشاف",
		navGroupIntegrations: "التكاملات",
		navGroupOperations: "العمليات",
		navHeadlessCmsPanel: "لوحة CMS بدون واجهة",
		navSocialSyndication: "النشر الاجتماعي",
	},
};
