#!/usr/bin/env bun
/**
 * audit-schema-migration-robustness — surface drift between the SQLite
 * baseline schema and the D1 migration paths, plus migration directory
 * gaps (.down.sql companions).
 *
 * Discovery only.
 */

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

const SQLITE_SCHEMA = "packages/astropress/src/sqlite-schema.sql";
const OUT = "tooling/audit-output/schema-migration-robustness.json";

function tablesIn(sql: string): string[] {
	return [...sql.matchAll(/CREATE\s+TABLE(?:\s+IF\s+NOT\s+EXISTS)?\s+(\w+)/gi)]
		.map((m) => m[1])
		.sort();
}

function listMigrations(dir: string): { up: string[]; downs: string[] } {
	if (!existsSync(dir)) return { up: [], downs: [] };
	const all = execFileSync("bash", ["-c", `find ${dir} -name "*.sql"`], {
		encoding: "utf8",
	})
		.split("\n")
		.filter(Boolean);
	return {
		up: all.filter((p) => !p.endsWith(".down.sql")).sort(),
		downs: all.filter((p) => p.endsWith(".down.sql")).sort(),
	};
}

const sqliteSchema = readFileSync(SQLITE_SCHEMA, "utf8");
const sqliteTables = tablesIn(sqliteSchema);

// D1 path: collect CREATE TABLE strings from any d1-*.ts file source AND
// from the committed d1-schema.sql baseline (the framework's source of
// truth for the D1 dialect; generated from sqlite-schema.sql).
const d1Sources = execFileSync(
	"bash",
	["-c", "cat packages/astropress/src/d1-*.ts packages/astropress/src/d1-schema.sql 2>/dev/null"],
	{ encoding: "utf8" },
);
const d1Tables = [...new Set(tablesIn(d1Sources))];

// Freshness check: re-run the generator in memory and compare against the
// committed file. If they differ, the generator wasn't run before commit.
function freshD1SchemaWouldBe(): string {
	const banner = `-- AUTOGENERATED from sqlite-schema.sql by tooling/scripts/generate-d1-schema.ts
-- Do not edit by hand. Run: bun run tooling/scripts/generate-d1-schema.ts
-- Cloudflare D1 is SQLite-compatible at the DDL we ship; the generator
-- exists to give D1 hosts a single committed baseline whose parity with
-- the sqlite path is enforced by tests/d1-schema-parity.test.ts.
`;
	return `${banner}\n${sqliteSchema}`;
}
const D1_PATH = "packages/astropress/src/d1-schema.sql";
const d1Current = existsSync(D1_PATH) ? readFileSync(D1_PATH, "utf8") : "";
const d1Stale = d1Current !== freshD1SchemaWouldBe();

const onlyInSqlite = sqliteTables.filter((t) => !d1Tables.includes(t));
const onlyInD1 = d1Tables.filter((t) => !sqliteTables.includes(t));

// Migration .down.sql companions (host migrations dir does not yet exist
// in the framework — this is the host-app contract; framework only ships
// the baseline schema).
const migrations = listMigrations("packages/astropress/migrations");
const missingDowns: string[] = [];
for (const up of migrations.up) {
	const expected = up.replace(/\.sql$/, ".down.sql");
	if (!migrations.downs.includes(expected)) missingDowns.push(up);
}

const report = {
	generatedAt: new Date().toISOString(),
	sqliteTableCount: sqliteTables.length,
	d1TableCount: d1Tables.length,
	tablesOnlyInSqlite: onlyInSqlite,
	tablesOnlyInD1: onlyInD1,
	hostMigrations: {
		upFiles: migrations.up.length,
		downFiles: migrations.downs.length,
		missingDownCompanions: missingDowns,
	},
};

if (!existsSync(dirname(OUT))) mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, `${JSON.stringify(report, null, 2)}\n`);
console.log(
	`schema-migration: sqlite-tables=${sqliteTables.length} d1-tables=${d1Tables.length} sqlite-only=${onlyInSqlite.length} d1-only=${onlyInD1.length} d1-stale=${d1Stale}`,
);

// Gate: any sqlite-only table or stale d1-schema.sql is a production-drift
// risk. D1 hosts must apply the same DDL as the sqlite path, and the
// generated baseline must reflect the latest sqlite-schema.sql.
if (onlyInSqlite.length > 0 || onlyInD1.length > 0 || d1Stale) {
	console.error("schema-migration FAIL:");
	if (onlyInSqlite.length > 0) console.error(`  sqlite-only tables: ${onlyInSqlite.join(", ")}`);
	if (onlyInD1.length > 0) console.error(`  d1-only tables: ${onlyInD1.join(", ")}`);
	if (d1Stale)
		console.error("  d1-schema.sql is stale — run: bun run tooling/scripts/generate-d1-schema.ts");
	process.exit(1);
}
