#!/usr/bin/env bun
/**
 * generate-d1-schema — emit packages/astropress/src/d1-schema.sql by
 * transforming the sqlite baseline. Cloudflare D1 is SQLite-compatible at
 * the DDL level we use here (INTEGER PRIMARY KEY AUTOINCREMENT, TEXT,
 * REAL, BLOB, CURRENT_TIMESTAMP defaults), so the transform is a verbatim
 * copy with a generation banner. If a future divergence appears, drop the
 * dialect rewrites in transformForD1() below.
 *
 * Idempotent: re-running with an unchanged input produces an identical
 * output. Pre-commit gates the freshness via content hash.
 */

import { readFileSync, writeFileSync } from "node:fs";

const SQLITE = "packages/astropress/src/sqlite-schema.sql";
const D1 = "packages/astropress/src/d1-schema.sql";

const BANNER = `-- AUTOGENERATED from sqlite-schema.sql by tooling/scripts/generate-d1-schema.ts
-- Do not edit by hand. Run: bun run tooling/scripts/generate-d1-schema.ts
-- Cloudflare D1 is SQLite-compatible at the DDL we ship; the generator
-- exists to give D1 hosts a single committed baseline whose parity with
-- the sqlite path is enforced by tests/d1-schema-parity.test.ts.
`;

function transformForD1(sqlite: string): string {
	// Placeholder for future divergences. Today: no rewrites needed.
	return sqlite;
}

function main(): void {
	const sqlite = readFileSync(SQLITE, "utf8");
	const out = `${BANNER}\n${transformForD1(sqlite)}`;
	writeFileSync(D1, out);
	const tableCount = (out.match(/CREATE\s+TABLE/gi) ?? []).length;
	console.log(`d1-schema written: ${tableCount} tables`);
}

main();
