import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const SQLITE = fileURLToPath(new URL("../src/sqlite-schema.sql", import.meta.url));
const D1 = fileURLToPath(new URL("../src/d1-schema.sql", import.meta.url));

type TableSpec = { name: string; columns: string[] };

function parse(sql: string): TableSpec[] {
	const stripped = sql.replace(/--[^\n]*\n/g, "\n");
	const tableRe = /CREATE\s+TABLE(?:\s+IF\s+NOT\s+EXISTS)?\s+(\w+)\s*\(([\s\S]*?)\n\)\s*;/gi;
	const out: TableSpec[] = [];
	let m: RegExpExecArray | null;
	while (true) {
		m = tableRe.exec(stripped);
		if (m === null) break;
		const name = m[1];
		const body = m[2];
		const columns = body
			.split(/,\n/)
			.map((line) => line.trim())
			.filter(
				(line) =>
					line.length > 0 && !/^(PRIMARY KEY|FOREIGN KEY|UNIQUE|CHECK|CONSTRAINT)\b/i.test(line),
			)
			.map((line) => line.split(/\s+/)[0]);
		out.push({ name, columns });
	}
	return out.sort((a, b) => a.name.localeCompare(b.name));
}

describe("d1 schema parity with sqlite baseline", () => {
	const sqlite = parse(readFileSync(SQLITE, "utf8"));
	const d1 = parse(readFileSync(D1, "utf8"));

	it("table sets are identical", () => {
		expect(d1.map((t) => t.name)).toEqual(sqlite.map((t) => t.name));
	});

	it("each table has identical column sets", () => {
		const sqliteByName = new Map(sqlite.map((t) => [t.name, t.columns]));
		const drift: string[] = [];
		for (const t of d1) {
			const sCols = sqliteByName.get(t.name) ?? [];
			const onlyInD1 = t.columns.filter((c) => !sCols.includes(c));
			const onlyInSqlite = sCols.filter((c) => !t.columns.includes(c));
			if (onlyInD1.length > 0 || onlyInSqlite.length > 0) {
				drift.push(
					`${t.name}: d1-only=[${onlyInD1.join(",")}] sqlite-only=[${onlyInSqlite.join(",")}]`,
				);
			}
		}
		expect(drift).toEqual([]);
	});

	it("d1-schema.sql carries the autogenerated banner so hand-edits are obvious", () => {
		const head = readFileSync(D1, "utf8").slice(0, 200);
		expect(head).toContain("AUTOGENERATED");
		expect(head).toContain("generate-d1-schema.ts");
	});
});
