//! Commerce, payments, and form services.

// ── Medusa ────────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_MEDUSA: &str = concat!(
    "# Medusa — headless commerce (MIT).\n",
    "# Usage: cp .env.medusa.example .env.medusa && docker compose --env-file .env.medusa up -d\n",
    "services:\n",
    "  medusa:\n",
    "    image: node:20-alpine\n",
    "    working_dir: /app\n",
    "    command: sh -c \"npm install && npm run build && npm start\"\n",
    "    ports:\n",
    "      - \"9000:9000\"\n",
    "    environment:\n",
    "      DATABASE_URL: \"postgres://medusa:${DB_PASSWORD}@db:5432/medusa\"\n",
    "      REDIS_URL: \"redis://redis:6379\"\n",
    "      JWT_SECRET: \"${JWT_SECRET:?set JWT_SECRET in .env.medusa}\"\n",
    "      COOKIE_SECRET: \"${COOKIE_SECRET:?set COOKIE_SECRET in .env.medusa}\"\n",
    "    volumes:\n",
    "      - ../:/app\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "      redis:\n",
    "        condition: service_started\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    image: postgres:16-alpine\n",
    "    environment:\n",
    "      POSTGRES_USER: medusa\n",
    "      POSTGRES_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.medusa}\"\n",
    "      POSTGRES_DB: medusa\n",
    "    volumes:\n",
    "      - medusa_db:/var/lib/postgresql/data\n",
    "    healthcheck:\n",
    "      test: [\"CMD-SHELL\", \"pg_isready -U medusa\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 5\n",
    "    restart: unless-stopped\n",
    "\n",
    "  redis:\n",
    "    image: redis:7-alpine\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  medusa_db:\n",
);
pub(super) const ENV_MEDUSA: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "JWT_SECRET=change-me-long-random-string\n",
    "COOKIE_SECRET=change-me-long-random-string\n",
);


// ── Vendure ───────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_VENDURE: &str = concat!(
    "# Vendure — TypeScript-first headless commerce (MIT).\n",
    "# Usage: cp .env.vendure.example .env.vendure && docker compose --env-file .env.vendure up -d\n",
    "services:\n",
    "  vendure:\n",
    "    image: node:20-alpine\n",
    "    working_dir: /app\n",
    "    command: sh -c \"npm install && npm run build && npm start\"\n",
    "    ports:\n",
    "      - \"3000:3000\"\n",
    "    environment:\n",
    "      DB_HOST: db\n",
    "      DB_PORT: \"5432\"\n",
    "      DB_USERNAME: vendure\n",
    "      DB_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.vendure}\"\n",
    "      DB_NAME: vendure\n",
    "      SUPERADMIN_USERNAME: \"${SUPERADMIN_USERNAME:-superadmin}\"\n",
    "      SUPERADMIN_PASSWORD: \"${SUPERADMIN_PASSWORD:?set SUPERADMIN_PASSWORD in .env.vendure}\"\n",
    "    volumes:\n",
    "      - ../:/app\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    image: postgres:16-alpine\n",
    "    environment:\n",
    "      POSTGRES_USER: vendure\n",
    "      POSTGRES_PASSWORD: \"${DB_PASSWORD}\"\n",
    "      POSTGRES_DB: vendure\n",
    "    volumes:\n",
    "      - vendure_db:/var/lib/postgresql/data\n",
    "    healthcheck:\n",
    "      test: [\"CMD-SHELL\", \"pg_isready -U vendure\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 5\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  vendure_db:\n",
);
pub(super) const ENV_VENDURE: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "SUPERADMIN_PASSWORD=change-me\n",
);


// ── HyperSwitch ───────────────────────────────────────────────────────────────

pub(super) const COMPOSE_HYPERSWITCH: &str = concat!(
    "# HyperSwitch — open-source payment orchestration (Apache 2.0).\n",
    "# Full deployment guide: https://docs.hyperswitch.io/hyperswitch-open-source/deploy-hyperswitch\n",
    "# Usage: cp .env.hyperswitch.example .env.hyperswitch && docker compose --env-file .env.hyperswitch up -d\n",
    "services:\n",
    "  hyperswitch-server:\n",
    "    image: juspaydotin/hyperswitch-router:latest\n",
    "    ports:\n",
    "      - \"8080:8080\"\n",
    "    environment:\n",
    "      ROUTER__SERVER__BASE_URL: \"${HYPERSWITCH_BASE_URL:?set HYPERSWITCH_BASE_URL}\"\n",
    "      ROUTER__MASTER_DATABASE__URL: \"postgres://hs:${DB_PASSWORD}@db:5432/hyperswitch\"\n",
    "      ROUTER__SECRETS__JWT_SECRET: \"${JWT_SECRET:?set JWT_SECRET}\"\n",
    "      ROUTER__SECRETS__ADMIN_API_KEY: \"${HYPERSWITCH_API_KEY:?set HYPERSWITCH_API_KEY}\"\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "      redis:\n",
    "        condition: service_started\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    image: postgres:16-alpine\n",
    "    environment:\n",
    "      POSTGRES_USER: hs\n",
    "      POSTGRES_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD}\"\n",
    "      POSTGRES_DB: hyperswitch\n",
    "    volumes:\n",
    "      - hs_db:/var/lib/postgresql/data\n",
    "    healthcheck:\n",
    "      test: [\"CMD-SHELL\", \"pg_isready -U hs\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 5\n",
    "    restart: unless-stopped\n",
    "\n",
    "  redis:\n",
    "    image: redis:7-alpine\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  hs_db:\n",
);
pub(super) const ENV_HYPERSWITCH: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "JWT_SECRET=change-me-long-random-string\n",
    "HYPERSWITCH_API_KEY=change-me\n",
    "HYPERSWITCH_BASE_URL=https://payments.yourdomain.com\n",
);


// ── Typebot ───────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_TYPEBOT: &str = concat!(
    "# Typebot — conversational forms + chatbot builder (AGPL 3.0).\n",
    "# Free cloud tier at https://typebot.io (recommended for most users).\n",
    "# Usage: cp .env.typebot.example .env.typebot && docker compose --env-file .env.typebot up -d\n",
    "services:\n",
    "  typebot-builder:\n",
    "    image: baptistearno/typebot-builder:latest\n",
    "    ports:\n",
    "      - \"3000:3000\"\n",
    "    environment:\n",
    "      DATABASE_URL: \"postgresql://typebot:${DB_PASSWORD}@db:5432/typebot\"\n",
    "      NEXTAUTH_URL: \"${TYPEBOT_BUILDER_URL:?set TYPEBOT_BUILDER_URL in .env.typebot}\"\n",
    "      NEXTAUTH_SECRET: \"${NEXTAUTH_SECRET:?set NEXTAUTH_SECRET in .env.typebot}\"\n",
    "      ENCRYPTION_SECRET: \"${ENCRYPTION_SECRET:?set ENCRYPTION_SECRET in .env.typebot}\"\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "    restart: unless-stopped\n",
    "\n",
    "  typebot-viewer:\n",
    "    image: baptistearno/typebot-viewer:latest\n",
    "    ports:\n",
    "      - \"3001:3000\"\n",
    "    environment:\n",
    "      DATABASE_URL: \"postgresql://typebot:${DB_PASSWORD}@db:5432/typebot\"\n",
    "      NEXTAUTH_URL: \"${TYPEBOT_VIEWER_URL:?set TYPEBOT_VIEWER_URL in .env.typebot}\"\n",
    "      NEXTAUTH_SECRET: \"${NEXTAUTH_SECRET}\"\n",
    "      ENCRYPTION_SECRET: \"${ENCRYPTION_SECRET}\"\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    image: postgres:16-alpine\n",
    "    environment:\n",
    "      POSTGRES_USER: typebot\n",
    "      POSTGRES_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.typebot}\"\n",
    "      POSTGRES_DB: typebot\n",
    "    volumes:\n",
    "      - typebot_db:/var/lib/postgresql/data\n",
    "    healthcheck:\n",
    "      test: [\"CMD-SHELL\", \"pg_isready -U typebot\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 5\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  typebot_db:\n",
);
pub(super) const ENV_TYPEBOT: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "NEXTAUTH_SECRET=change-me-32-char-random-string\n",
    "ENCRYPTION_SECRET=change-me-32-char-random-string\n",
    "TYPEBOT_BUILDER_URL=https://typebot.yourdomain.com\n",
    "TYPEBOT_VIEWER_URL=https://bot.yourdomain.com\n",
);


// ── Formbricks ────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_FORMBRICKS: &str = concat!(
    "# Formbricks — surveys + NPS + testimonials (MIT community edition).\n",
    "# Free cloud tier at https://formbricks.com (recommended for most users).\n",
    "# Usage: cp .env.formbricks.example .env.formbricks && docker compose --env-file .env.formbricks up -d\n",
    "services:\n",
    "  formbricks:\n",
    "    image: formbricks/formbricks:latest\n",
    "    ports:\n",
    "      - \"3000:3000\"\n",
    "    environment:\n",
    "      DATABASE_URL: \"postgresql://formbricks:${DB_PASSWORD}@db:5432/formbricks\"\n",
    "      NEXTAUTH_URL: \"${FORMBRICKS_URL:?set FORMBRICKS_URL in .env.formbricks}\"\n",
    "      NEXTAUTH_SECRET: \"${NEXTAUTH_SECRET:?set NEXTAUTH_SECRET in .env.formbricks}\"\n",
    "      ENCRYPTION_KEY: \"${ENCRYPTION_KEY:?set ENCRYPTION_KEY in .env.formbricks}\"\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    image: postgres:16-alpine\n",
    "    environment:\n",
    "      POSTGRES_USER: formbricks\n",
    "      POSTGRES_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.formbricks}\"\n",
    "      POSTGRES_DB: formbricks\n",
    "    volumes:\n",
    "      - formbricks_db:/var/lib/postgresql/data\n",
    "    healthcheck:\n",
    "      test: [\"CMD-SHELL\", \"pg_isready -U formbricks\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 5\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  formbricks_db:\n",
);
pub(super) const ENV_FORMBRICKS: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "NEXTAUTH_SECRET=change-me-32-char-random-string\n",
    "ENCRYPTION_KEY=change-me-32-char-random-string\n",
    "FORMBRICKS_URL=https://forms.yourdomain.com\n",
);

