//! Communication services: newsletter, transactional email, push, chat, comments.

// ── Listmonk ──────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_LISTMONK: &str = concat!(
    "# Listmonk + Caddy reverse proxy + Postgres.\n",
    "# Caddy strips X-Frame-Options so Listmonk can be embedded in the Astropress admin panel.\n",
    "#\n",
    "# Usage:\n",
    "#   cp .env.listmonk.example .env.listmonk\n",
    "#   # Edit .env.listmonk and set DB_PASSWORD and SITE_URL\n",
    "#   docker compose --env-file .env.listmonk up -d\n",
    "#\n",
    "# Deploy to Railway: connect this directory as a Docker Compose service.\n",
    "# Deploy to Fly.io:  cd listmonk && fly launch && fly deploy\n",
    "services:\n",
    "  caddy:\n",
    "    image: caddy:2-alpine\n",
    "    ports:\n",
    "      - \"80:80\"\n",
    "      - \"443:443\"\n",
    "    volumes:\n",
    "      - ./Caddyfile:/etc/caddy/Caddyfile\n",
    "      - caddy_data:/data\n",
    "    environment:\n",
    "      SITE_URL: \"${SITE_URL:-https://example.com}\"\n",
    "    depends_on:\n",
    "      - listmonk\n",
    "    restart: unless-stopped\n",
    "\n",
    "  listmonk:\n",
    "    image: listmonk/listmonk:latest\n",
    "    environment:\n",
    "      LISTMONK_app__address: \"0.0.0.0:9000\"\n",
    "      LISTMONK_db__host: db\n",
    "      LISTMONK_db__port: \"5432\"\n",
    "      LISTMONK_db__user: listmonk\n",
    "      LISTMONK_db__password: \"${DB_PASSWORD:?set DB_PASSWORD in .env.listmonk}\"\n",
    "      LISTMONK_db__database: listmonk\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    image: postgres:16-alpine\n",
    "    environment:\n",
    "      POSTGRES_USER: listmonk\n",
    "      POSTGRES_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.listmonk}\"\n",
    "      POSTGRES_DB: listmonk\n",
    "    volumes:\n",
    "      - listmonk_db:/var/lib/postgresql/data\n",
    "    healthcheck:\n",
    "      test: [\"CMD-SHELL\", \"pg_isready -U listmonk\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 5\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  caddy_data:\n",
    "  listmonk_db:\n",
);

pub(super) const ENV_LISTMONK: &str = concat!(
    "# Copy to .env.listmonk and fill in real values before running docker compose.\n",
    "DB_PASSWORD=change-me\n",
    "SITE_URL=https://your-astropress-site.example.com\n",
);

pub(super) const CADDYFILE_LISTMONK: &str = concat!(
    "# Caddy reverse proxy for Listmonk.\n",
    "# Strips X-Frame-Options: SAMEORIGIN so the Listmonk admin can be embedded\n",
    "# in the Astropress admin panel at /ap-admin/services/email.\n",
    "# SITE_URL must be set to your Astropress site's public URL (e.g. https://example.com).\n",
    "{\n",
    "    admin off\n",
    "}\n",
    "\n",
    ":80 {\n",
    "    reverse_proxy listmonk:9000 {\n",
    "        header_down -X-Frame-Options\n",
    "    }\n",
    "    header {\n",
    "        Content-Security-Policy \"frame-ancestors 'self' {$SITE_URL}\"\n",
    "    }\n",
    "}\n",
);

// ── Postal ────────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_POSTAL: &str = concat!(
    "# Postal — self-hosted SMTP server (MIT).\n",
    "# ⚠ For best email deliverability, Postal needs a dedicated IP address.\n",
    "#   On Fly.io: use a dedicated-vm machine. On Railway: use a static outbound IP add-on.\n",
    "# ⚠ Requires ~512 MB RAM across all three services — Fly.io shared-cpu-1x with 512 MB works; Railway $5/mo.\n",
    "# Full guide: https://docs.postalserver.io/install/installation\n",
    "# Usage: cp .env.postal.example .env.postal && docker compose --env-file .env.postal up -d\n",
    "services:\n",
    "  postal:\n",
    "    image: ghcr.io/postalserver/postal:latest\n",
    "    ports:\n",
    "      - \"25:25\"    # SMTP inbound\n",
    "      - \"587:587\"  # SMTP submission\n",
    "      - \"5000:5000\" # Web UI\n",
    "    environment:\n",
    "      POSTAL_DATABASE_HOST: db\n",
    "      POSTAL_DATABASE_USERNAME: postal\n",
    "      POSTAL_DATABASE_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.postal}\"\n",
    "      POSTAL_RABBITMQ_HOST: rabbitmq\n",
    "      POSTAL_SECRET_KEY: \"${SECRET_KEY:?set SECRET_KEY in .env.postal}\"\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "      rabbitmq:\n",
    "        condition: service_started\n",
    "    volumes:\n",
    "      - postal_data:/config\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    # mariadb:11 uses ~100 MB idle vs MySQL 8's ~300 MB — better fit for free tiers.\n",
    "    image: mariadb:11\n",
    "    environment:\n",
    "      MYSQL_DATABASE: postal\n",
    "      MYSQL_USER: postal\n",
    "      MYSQL_PASSWORD: \"${DB_PASSWORD}\"\n",
    "      MYSQL_ROOT_PASSWORD: \"${DB_ROOT_PASSWORD:-rootpass}\"\n",
    "    volumes:\n",
    "      - postal_db:/var/lib/mysql\n",
    "    healthcheck:\n",
    "      test: [\"CMD\", \"mysqladmin\", \"ping\", \"-h\", \"localhost\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 10\n",
    "    restart: unless-stopped\n",
    "\n",
    "  rabbitmq:\n",
    "    image: rabbitmq:3-management-alpine\n",
    "    volumes:\n",
    "      - postal_rabbitmq:/var/lib/rabbitmq\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  postal_data:\n",
    "  postal_db:\n",
    "  postal_rabbitmq:\n",
);
pub(super) const ENV_POSTAL: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "DB_ROOT_PASSWORD=change-me-root\n",
    "SECRET_KEY=change-me-long-random-string\n",
);


// ── Gotify ────────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_GOTIFY: &str = concat!(
    "# Gotify — self-hosted push notifications (MIT).\n",
    "# Usage: cp .env.gotify.example .env.gotify && docker compose --env-file .env.gotify up -d\n",
    "services:\n",
    "  gotify:\n",
    "    image: gotify/server:latest\n",
    "    ports:\n",
    "      - \"80:80\"\n",
    "    environment:\n",
    "      GOTIFY_DEFAULTUSER_PASS: \"${GOTIFY_ADMIN_PASS:?set GOTIFY_ADMIN_PASS in .env.gotify}\"\n",
    "    volumes:\n",
    "      - gotify_data:/app/data\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  gotify_data:\n",
);
pub(super) const ENV_GOTIFY: &str = concat!(
    "GOTIFY_ADMIN_PASS=change-me\n",
);


// ── Tiledesk ──────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_TILEDESK: &str = concat!(
    "# Tiledesk — live chat + helpdesk (Apache 2.0).\n",
    "# Free tier: Fly.io shared-cpu-1x with 512 MB.\n",
    "# Full compose: https://github.com/Tiledesk/tiledesk-deployment\n",
    "# Usage: cp .env.tiledesk.example .env.tiledesk && docker compose --env-file .env.tiledesk up -d\n",
    "services:\n",
    "  tiledesk:\n",
    "    image: tiledesk/tiledesk-server:latest\n",
    "    ports:\n",
    "      - \"8080:8080\"\n",
    "    environment:\n",
    "      MONGODB_URI: \"mongodb://mongo:27017/tiledesk\"\n",
    "      JWT_SECRET: \"${JWT_SECRET:?set JWT_SECRET in .env.tiledesk}\"\n",
    "      APP_BASE_URL: \"${TILEDESK_URL:?set TILEDESK_URL in .env.tiledesk}\"\n",
    "    depends_on:\n",
    "      - mongo\n",
    "    restart: unless-stopped\n",
    "\n",
    "  mongo:\n",
    "    image: mongo:6\n",
    "    # Cap the WiredTiger cache to 256 MB so MongoDB fits on free-tier VMs.\n",
    "    command: [\"mongod\", \"--wiredTigerCacheSizeGB\", \"0.25\"]\n",
    "    volumes:\n",
    "      - tiledesk_db:/data/db\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  tiledesk_db:\n",
);
pub(super) const ENV_TILEDESK: &str = concat!(
    "JWT_SECRET=change-me-long-random-string\n",
    "TILEDESK_URL=https://chat.yourdomain.com\n",
);


// ── Chatwoot ──────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_CHATWOOT: &str = concat!(
    "# Chatwoot — omnichannel customer support (MIT).\n",
    "# Usage: cp .env.chatwoot.example .env.chatwoot && docker compose --env-file .env.chatwoot up -d\n",
    "services:\n",
    "  chatwoot-server:\n",
    "    image: chatwoot/chatwoot:latest\n",
    "    command: bundle exec rails s -p 3000 -b 0.0.0.0\n",
    "    ports:\n",
    "      - \"3000:3000\"\n",
    "    environment:\n",
    "      RAILS_ENV: production\n",
    "      SECRET_KEY_BASE: \"${SECRET_KEY_BASE:?set SECRET_KEY_BASE in .env.chatwoot}\"\n",
    "      DATABASE_URL: \"postgres://chatwoot:${DB_PASSWORD}@db:5432/chatwoot_production\"\n",
    "      REDIS_URL: \"redis://redis:6379\"\n",
    "      FRONTEND_URL: \"${CHATWOOT_URL:?set CHATWOOT_URL in .env.chatwoot}\"\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "      redis:\n",
    "        condition: service_started\n",
    "    restart: unless-stopped\n",
    "\n",
    "  chatwoot-worker:\n",
    "    image: chatwoot/chatwoot:latest\n",
    "    command: bundle exec sidekiq -C config/sidekiq.yml\n",
    "    environment:\n",
    "      RAILS_ENV: production\n",
    "      SECRET_KEY_BASE: \"${SECRET_KEY_BASE}\"\n",
    "      DATABASE_URL: \"postgres://chatwoot:${DB_PASSWORD}@db:5432/chatwoot_production\"\n",
    "      REDIS_URL: \"redis://redis:6379\"\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "      redis:\n",
    "        condition: service_started\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    image: postgres:16-alpine\n",
    "    environment:\n",
    "      POSTGRES_USER: chatwoot\n",
    "      POSTGRES_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.chatwoot}\"\n",
    "      POSTGRES_DB: chatwoot_production\n",
    "    volumes:\n",
    "      - chatwoot_db:/var/lib/postgresql/data\n",
    "    healthcheck:\n",
    "      test: [\"CMD-SHELL\", \"pg_isready -U chatwoot\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 5\n",
    "    restart: unless-stopped\n",
    "\n",
    "  redis:\n",
    "    image: redis:7-alpine\n",
    "    volumes:\n",
    "      - chatwoot_redis:/data\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  chatwoot_db:\n",
    "  chatwoot_redis:\n",
);
pub(super) const ENV_CHATWOOT: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "SECRET_KEY_BASE=change-me-long-random-string\n",
    "CHATWOOT_URL=https://support.yourdomain.com\n",
);


// ── Remark42 ──────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_REMARK42: &str = concat!(
    "# Remark42 — self-hosted comments (MIT).\n",
    "# Usage: cp .env.remark42.example .env.remark42 && docker compose --env-file .env.remark42 up -d\n",
    "services:\n",
    "  remark42:\n",
    "    image: umputun/remark42:latest\n",
    "    ports:\n",
    "      - \"8080:8080\"\n",
    "    environment:\n",
    "      REMARK_URL: \"${REMARK_URL:?set REMARK_URL in .env.remark42}\"\n",
    "      SECRET: \"${REMARK_SECRET:?set REMARK_SECRET in .env.remark42}\"\n",
    "      AUTH_ANON: \"true\"\n",
    "    volumes:\n",
    "      - remark42_data:/srv/var\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  remark42_data:\n",
);
pub(super) const ENV_REMARK42: &str = concat!(
    "REMARK_URL=https://comments.yourdomain.com\n",
    "REMARK_SECRET=change-me-long-random-string\n",
);

