//! Content services: CMS, search, forum, knowledge base.

// ── Payload CMS ───────────────────────────────────────────────────────────────

pub(super) const COMPOSE_PAYLOAD: &str = concat!(
    "# Payload CMS + Postgres.\n",
    "# Usage: cp .env.payload.example .env.payload && docker compose --env-file .env.payload up -d\n",
    "services:\n",
    "  payload:\n",
    "    image: node:20-alpine\n",
    "    working_dir: /app\n",
    "    command: sh -c \"npm install && npm run build && npm start\"\n",
    "    ports:\n",
    "      - \"3000:3000\"\n",
    "    environment:\n",
    "      DATABASE_URI: \"postgres://payload:${DB_PASSWORD}@db:5432/payload\"\n",
    "      PAYLOAD_SECRET: \"${PAYLOAD_SECRET:?set PAYLOAD_SECRET in .env.payload}\"\n",
    "      PAYLOAD_PUBLIC_SERVER_URL: \"${PAYLOAD_URL:-http://localhost:3000}\"\n",
    "    volumes:\n",
    "      - ../:/app\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    image: postgres:16-alpine\n",
    "    environment:\n",
    "      POSTGRES_USER: payload\n",
    "      POSTGRES_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.payload}\"\n",
    "      POSTGRES_DB: payload\n",
    "    volumes:\n",
    "      - payload_db:/var/lib/postgresql/data\n",
    "    healthcheck:\n",
    "      test: [\"CMD-SHELL\", \"pg_isready -U payload\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 5\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  payload_db:\n",
);
pub(super) const ENV_PAYLOAD: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "PAYLOAD_SECRET=change-me-long-random-string\n",
    "PAYLOAD_URL=https://cms.yourdomain.com\n",
);


// ── Meilisearch ───────────────────────────────────────────────────────────────

pub(super) const COMPOSE_MEILISEARCH: &str = concat!(
    "# Meilisearch — typo-tolerant full-text search (MIT).\n",
    "# Usage: cp .env.meilisearch.example .env.meilisearch && docker compose --env-file .env.meilisearch up -d\n",
    "services:\n",
    "  meilisearch:\n",
    "    image: getmeili/meilisearch:latest\n",
    "    ports:\n",
    "      - \"7700:7700\"\n",
    "    environment:\n",
    "      MEILI_MASTER_KEY: \"${MEILI_MASTER_KEY:?set MEILI_MASTER_KEY in .env.meilisearch}\"\n",
    "    volumes:\n",
    "      - meili_data:/meili_data\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  meili_data:\n",
);
pub(super) const ENV_MEILISEARCH: &str = concat!(
    "MEILI_MASTER_KEY=change-me-long-random-string\n",
);


// ── Flarum ────────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_FLARUM: &str = concat!(
    "# Flarum — lightweight forum (MIT, PHP).\n",
    "# Free tier: Railway free (512 MB RAM) or Fly.io shared-cpu-1x (256 MB) — fits comfortably.\n",
    "# Usage: cp .env.flarum.example .env.flarum && docker compose --env-file .env.flarum up -d\n",
    "services:\n",
    "  flarum:\n",
    "    image: crazymax/flarum:latest\n",
    "    ports:\n",
    "      - \"8080:8000\"\n",
    "    environment:\n",
    "      DB_HOST: db\n",
    "      DB_NAME: flarum\n",
    "      DB_USER: flarum\n",
    "      DB_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.flarum}\"\n",
    "      FLARUM_BASE_URL: \"${FLARUM_BASE_URL:?set FLARUM_BASE_URL in .env.flarum}\"\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "    volumes:\n",
    "      - flarum_data:/data\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    # mariadb:11 uses ~100 MB idle vs MySQL 8's ~300 MB — better fit for free tiers.\n",
    "    image: mariadb:11\n",
    "    environment:\n",
    "      MYSQL_DATABASE: flarum\n",
    "      MYSQL_USER: flarum\n",
    "      MYSQL_PASSWORD: \"${DB_PASSWORD}\"\n",
    "      MYSQL_ROOT_PASSWORD: \"${DB_ROOT_PASSWORD:-rootpass}\"\n",
    "    volumes:\n",
    "      - flarum_db:/var/lib/mysql\n",
    "    healthcheck:\n",
    "      test: [\"CMD\", \"mysqladmin\", \"ping\", \"-h\", \"localhost\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 10\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  flarum_data:\n",
    "  flarum_db:\n",
);
pub(super) const ENV_FLARUM: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "DB_ROOT_PASSWORD=change-me-root\n",
    "FLARUM_BASE_URL=https://forum.yourdomain.com\n",
);


// ── Discourse ─────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_DISCOURSE: &str = concat!(
    "# Discourse — mature forum (GPL 2.0, Ruby).\n",
    "# ⚠ Discourse officially recommends its own install script (discourse-setup),\n",
    "#   not a custom docker-compose. Use the official guide:\n",
    "#   https://github.com/discourse/discourse/blob/main/docs/INSTALL-cloud.md\n",
    "#\n",
    "# Minimum requirements: 2 GB RAM, 2 CPUs (Fly.io performance-2x or Railway Pro).\n",
    "#\n",
    "# Lightweight alternative: use Flarum (see above) — much lower resource footprint.\n",
    "services:\n",
    "  discourse:\n",
    "    image: discourse/base:release\n",
    "    ports:\n",
    "      - \"80:80\"\n",
    "      - \"443:443\"\n",
    "    environment:\n",
    "      DISCOURSE_HOSTNAME: \"${DISCOURSE_URL:?set DISCOURSE_URL in .env.discourse}\"\n",
    "      DISCOURSE_DEVELOPER_EMAILS: \"${ADMIN_EMAIL:?set ADMIN_EMAIL in .env.discourse}\"\n",
    "      DISCOURSE_SMTP_ADDRESS: \"${SMTP_HOST:?set SMTP_HOST in .env.discourse}\"\n",
    "      DISCOURSE_SMTP_PORT: \"${SMTP_PORT:-587}\"\n",
    "      DISCOURSE_SMTP_USER_NAME: \"${SMTP_USER}\"\n",
    "      DISCOURSE_SMTP_PASSWORD: \"${SMTP_PASSWORD}\"\n",
    "    volumes:\n",
    "      - discourse_data:/var/www/discourse/public/uploads\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  discourse_data:\n",
);
pub(super) const ENV_DISCOURSE: &str = concat!(
    "DISCOURSE_URL=forum.yourdomain.com\n",
    "ADMIN_EMAIL=admin@yourdomain.com\n",
    "SMTP_HOST=smtp-relay.brevo.com\n",
    "SMTP_PORT=587\n",
    "SMTP_USER=your-brevo-login@example.com\n",
    "SMTP_PASSWORD=your-brevo-smtp-key\n",
);


// ── BookStack ─────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_BOOKSTACK: &str = concat!(
    "# BookStack — structured wiki and knowledge base (MIT).\n",
    "# Free tier: Railway free (512 MB RAM) or Fly.io shared-cpu-1x with 512 MB — fits comfortably.\n",
    "# Usage: cp .env.bookstack.example .env.bookstack && docker compose --env-file .env.bookstack up -d\n",
    "services:\n",
    "  bookstack:\n",
    "    image: lscr.io/linuxserver/bookstack:latest\n",
    "    ports:\n",
    "      - \"6875:80\"\n",
    "    environment:\n",
    "      APP_URL: \"${BOOKSTACK_URL:?set BOOKSTACK_URL in .env.bookstack}\"\n",
    "      DB_HOST: db\n",
    "      DB_DATABASE: bookstack\n",
    "      DB_USERNAME: bookstack\n",
    "      DB_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.bookstack}\"\n",
    "      MAIL_DRIVER: smtp\n",
    "      MAIL_HOST: \"${SMTP_HOST}\"\n",
    "      MAIL_PORT: \"${SMTP_PORT:-587}\"\n",
    "      MAIL_USERNAME: \"${SMTP_USER}\"\n",
    "      MAIL_PASSWORD: \"${SMTP_PASSWORD}\"\n",
    "      MAIL_FROM: \"${SMTP_FROM}\"\n",
    "    volumes:\n",
    "      - bookstack_data:/config\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    # mariadb:11 uses ~100 MB idle vs MySQL 8's ~300 MB — better fit for free tiers.\n",
    "    image: mariadb:11\n",
    "    environment:\n",
    "      MYSQL_DATABASE: bookstack\n",
    "      MYSQL_USER: bookstack\n",
    "      MYSQL_PASSWORD: \"${DB_PASSWORD}\"\n",
    "      MYSQL_ROOT_PASSWORD: \"${DB_ROOT_PASSWORD:-rootpass}\"\n",
    "    volumes:\n",
    "      - bookstack_db:/var/lib/mysql\n",
    "    healthcheck:\n",
    "      test: [\"CMD\", \"mysqladmin\", \"ping\", \"-h\", \"localhost\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 10\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  bookstack_data:\n",
    "  bookstack_db:\n",
);
pub(super) const ENV_BOOKSTACK: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "DB_ROOT_PASSWORD=change-me-root\n",
    "BOOKSTACK_URL=https://docs.yourdomain.com\n",
    "SMTP_HOST=smtp-relay.brevo.com\n",
    "SMTP_PORT=587\n",
    "SMTP_USER=your-brevo-login@example.com\n",
    "SMTP_PASSWORD=your-brevo-smtp-key\n",
    "SMTP_FROM=noreply@yourdomain.com\n",
);

