//! Identity (CRM, SSO), monitoring, and learning services.

// ── Uptime Kuma ───────────────────────────────────────────────────────────────

pub(super) const COMPOSE_UPTIME_KUMA: &str = concat!(
    "# Uptime Kuma — uptime monitoring + public status page (MIT).\n",
    "# Usage: docker compose up -d\n",
    "services:\n",
    "  uptime-kuma:\n",
    "    image: louislam/uptime-kuma:latest\n",
    "    ports:\n",
    "      - \"3001:3001\"\n",
    "    volumes:\n",
    "      - uptime_kuma_data:/app/data\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  uptime_kuma_data:\n",
);
pub(super) const ENV_UPTIME_KUMA: &str =
    "# No env vars needed — configure via the web UI after first launch.\n";


// ── Twenty CRM ────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_TWENTY: &str = concat!(
    "# Twenty — modern open-source CRM (AGPL 3.0).\n",
    "# ⚠ Requires ~4 GB RAM. Fly.io: performance-2x machine (paid). Railway Pro recommended.\n",
    "# Usage: cp .env.twenty.example .env.twenty && docker compose --env-file .env.twenty up -d\n",
    "services:\n",
    "  twenty-server:\n",
    "    image: twentycrm/twenty:latest\n",
    "    ports:\n",
    "      - \"3000:3000\"\n",
    "    environment:\n",
    "      SERVER_URL: \"${TWENTY_URL:?set TWENTY_URL in .env.twenty}\"\n",
    "      PG_DATABASE_URL: \"postgres://twenty:${DB_PASSWORD}@db:5432/twenty\"\n",
    "      REDIS_URL: \"redis://redis:6379\"\n",
    "      APP_SECRET: \"${APP_SECRET:?set APP_SECRET in .env.twenty}\"\n",
    "      STORAGE_TYPE: local\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "      redis:\n",
    "        condition: service_started\n",
    "    restart: unless-stopped\n",
    "\n",
    "  twenty-worker:\n",
    "    image: twentycrm/twenty:latest\n",
    "    command: worker\n",
    "    environment:\n",
    "      PG_DATABASE_URL: \"postgres://twenty:${DB_PASSWORD}@db:5432/twenty\"\n",
    "      REDIS_URL: \"redis://redis:6379\"\n",
    "      APP_SECRET: \"${APP_SECRET}\"\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "      redis:\n",
    "        condition: service_started\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    image: postgres:16-alpine\n",
    "    environment:\n",
    "      POSTGRES_USER: twenty\n",
    "      POSTGRES_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.twenty}\"\n",
    "      POSTGRES_DB: twenty\n",
    "    volumes:\n",
    "      - twenty_db:/var/lib/postgresql/data\n",
    "    healthcheck:\n",
    "      test: [\"CMD-SHELL\", \"pg_isready -U twenty\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 5\n",
    "    restart: unless-stopped\n",
    "\n",
    "  redis:\n",
    "    image: redis:7-alpine\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  twenty_db:\n",
);
pub(super) const ENV_TWENTY: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "APP_SECRET=change-me-long-random-string\n",
    "TWENTY_URL=https://crm.yourdomain.com\n",
);


// ── Authentik ─────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_AUTHENTIK: &str = concat!(
    "# Authentik — identity provider (MIT).\n",
    "# ⚠ Requires ~512 MB RAM. Borderline on Fly.io free tier (256 MB); use Fly.io 512 MB shared VM.\n",
    "# Full guide: https://docs.goauthentik.io/docs/installation/docker-compose\n",
    "# Usage: cp .env.authentik.example .env.authentik && docker compose --env-file .env.authentik up -d\n",
    "services:\n",
    "  authentik-server:\n",
    "    image: ghcr.io/goauthentik/server:latest\n",
    "    command: server\n",
    "    ports:\n",
    "      - \"9000:9000\"\n",
    "      - \"9443:9443\"\n",
    "    environment:\n",
    "      AUTHENTIK_REDIS__HOST: redis\n",
    "      AUTHENTIK_POSTGRESQL__HOST: db\n",
    "      AUTHENTIK_POSTGRESQL__USER: authentik\n",
    "      AUTHENTIK_POSTGRESQL__PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.authentik}\"\n",
    "      AUTHENTIK_POSTGRESQL__NAME: authentik\n",
    "      AUTHENTIK_SECRET_KEY: \"${SECRET_KEY:?set SECRET_KEY in .env.authentik}\"\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "      redis:\n",
    "        condition: service_started\n",
    "    restart: unless-stopped\n",
    "\n",
    "  authentik-worker:\n",
    "    image: ghcr.io/goauthentik/server:latest\n",
    "    command: worker\n",
    "    environment:\n",
    "      AUTHENTIK_REDIS__HOST: redis\n",
    "      AUTHENTIK_POSTGRESQL__HOST: db\n",
    "      AUTHENTIK_POSTGRESQL__USER: authentik\n",
    "      AUTHENTIK_POSTGRESQL__PASSWORD: \"${DB_PASSWORD}\"\n",
    "      AUTHENTIK_POSTGRESQL__NAME: authentik\n",
    "      AUTHENTIK_SECRET_KEY: \"${SECRET_KEY}\"\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "      redis:\n",
    "        condition: service_started\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    image: postgres:16-alpine\n",
    "    environment:\n",
    "      POSTGRES_USER: authentik\n",
    "      POSTGRES_PASSWORD: \"${DB_PASSWORD}\"\n",
    "      POSTGRES_DB: authentik\n",
    "    volumes:\n",
    "      - authentik_db:/var/lib/postgresql/data\n",
    "    healthcheck:\n",
    "      test: [\"CMD-SHELL\", \"pg_isready -U authentik\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 5\n",
    "    restart: unless-stopped\n",
    "\n",
    "  redis:\n",
    "    image: redis:7-alpine\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  authentik_db:\n",
);
pub(super) const ENV_AUTHENTIK: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "SECRET_KEY=change-me-long-random-string-at-least-50-chars\n",
);


// ── Zitadel ───────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_ZITADEL: &str = concat!(
    "# Zitadel — identity platform (Apache 2.0).\n",
    "# Free cloud tier at https://zitadel.com (recommended; generous free tier).\n",
    "# Full self-host guide: https://zitadel.com/docs/self-hosting/deploy/compose\n",
    "# Usage: cp .env.zitadel.example .env.zitadel && docker compose --env-file .env.zitadel up -d\n",
    "services:\n",
    "  zitadel:\n",
    "    image: ghcr.io/zitadel/zitadel:latest\n",
    "    ports:\n",
    "      - \"8080:8080\"\n",
    "    command: start-from-init --masterkey \"${ZITADEL_MASTERKEY:?set ZITADEL_MASTERKEY}\" --tlsMode disabled\n",
    "    environment:\n",
    "      ZITADEL_DATABASE_POSTGRES_HOST: db\n",
    "      ZITADEL_DATABASE_POSTGRES_PORT: \"5432\"\n",
    "      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel\n",
    "      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel\n",
    "      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.zitadel}\"\n",
    "      ZITADEL_EXTERNALPORT: \"8080\"\n",
    "      ZITADEL_EXTERNALDOMAIN: \"${ZITADEL_DOMAIN:?set ZITADEL_DOMAIN in .env.zitadel}\"\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    image: postgres:16-alpine\n",
    "    environment:\n",
    "      POSTGRES_USER: zitadel\n",
    "      POSTGRES_PASSWORD: \"${DB_PASSWORD}\"\n",
    "      POSTGRES_DB: zitadel\n",
    "    volumes:\n",
    "      - zitadel_db:/var/lib/postgresql/data\n",
    "    healthcheck:\n",
    "      test: [\"CMD-SHELL\", \"pg_isready -U zitadel\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 5\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  zitadel_db:\n",
);
pub(super) const ENV_ZITADEL: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "ZITADEL_MASTERKEY=change-me-32-char-random-string\n",
    "ZITADEL_DOMAIN=auth.yourdomain.com\n",
);


// ── Frappe LMS ────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_FRAPPE_LMS: &str = concat!(
    "# Frappe LMS — open-source courses and learning management (MIT).\n",
    "# ⚠ Requires ~512 MB RAM total. Fly.io shared-cpu-1x with 512 MB works.\n",
    "# Full guide: https://github.com/frappe/lms#installation\n",
    "# Usage: cp .env.frappe-lms.example .env.frappe-lms && docker compose --env-file .env.frappe-lms up -d\n",
    "services:\n",
    "  frappe-lms:\n",
    "    image: frappe/frappe-worker:latest\n",
    "    ports:\n",
    "      - \"8000:8000\"\n",
    "    environment:\n",
    "      FRAPPE_SITE_NAME_HEADER: \"${FRAPPE_SITE:?set FRAPPE_SITE in .env.frappe-lms}\"\n",
    "      REDIS_CACHE: \"redis://redis:6379/0\"\n",
    "      REDIS_QUEUE: \"redis://redis:6379/1\"\n",
    "      DB_HOST: db\n",
    "      DB_PORT: \"3306\"\n",
    "      MYSQL_ROOT_PASSWORD: \"${DB_ROOT_PASSWORD:?set DB_ROOT_PASSWORD in .env.frappe-lms}\"\n",
    "    volumes:\n",
    "      - frappe_sites:/home/frappe/frappe-bench/sites\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "      redis:\n",
    "        condition: service_started\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    # mariadb:10.11 (Frappe's recommended database) — uses ~100 MB idle vs MySQL 8's ~300 MB.\n",
    "    image: mariadb:10.11\n",
    "    environment:\n",
    "      MYSQL_ROOT_PASSWORD: \"${DB_ROOT_PASSWORD}\"\n",
    "    volumes:\n",
    "      - frappe_db:/var/lib/mysql\n",
    "    healthcheck:\n",
    "      test: [\"CMD\", \"mysqladmin\", \"ping\", \"-h\", \"localhost\", \"-uroot\", \"-p${DB_ROOT_PASSWORD}\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 10\n",
    "    restart: unless-stopped\n",
    "\n",
    "  redis:\n",
    "    image: redis:7-alpine\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  frappe_sites:\n",
    "  frappe_db:\n",
);
pub(super) const ENV_FRAPPE_LMS: &str = concat!(
    "FRAPPE_SITE=lms.yourdomain.com\n",
    "DB_ROOT_PASSWORD=change-me\n",
);

#[path = "identity_extra.rs"]
mod identity_extra;
pub(super) use identity_extra::{COMPOSE_FLAGSMITH, ENV_FLAGSMITH};
