//! `SERVICES.md` generator: per-service deploy instructions.
//!
//! Orchestrated by `service_docs::build_services_doc()` — this module owns
//! the string-builder for the unified markdown file. Later service sections
//! (commerce, forms, video, podcast, events, transactional email, status,
//! knowledge base, CRM, SSO, courses) live in `markdown_more.rs` to keep
//! each file under the 300-line arch-lint warning.

use crate::features::{
    AllFeatures, ChatChoice, CmsChoice, CommunityChoice, EmailChoice, ForumChoice,
    NotifyChoice, PaymentChoice, PodcastChoice, ScheduleChoice, SearchChoice,
    VideoChoice,
};
use super::service_compose_stubs;

#[path = "markdown_more.rs"]
mod markdown_more;

use markdown_more::append_more_services;

fn needs_flyio(f: &AllFeatures) -> bool {
    !service_compose_stubs(f).is_empty()
}

fn needs_r2(f: &AllFeatures) -> bool {
    f.video == VideoChoice::PeerTube || f.podcast == PodcastChoice::Castopod
}

/// Generates a unified `SERVICES.md` setup guide covering:
/// 1. Hosting accounts to set up first (Fly.io, Cloudflare R2 if needed)
/// 2. Per-service deploy steps for every selected self-hosted service
///
/// Returns `None` if no self-hosted services were selected.
pub(crate) fn build_services_doc(f: &AllFeatures) -> Option<String> {
    if service_compose_stubs(f).is_empty() {
        return None;
    }
    let mut doc = String::from(
        "# Services Setup Guide\n\
         \n\
         Generated by `astropress new`. Deploy your services in this order:\n\
         first set up your hosting accounts, then deploy each service.\n\
         \n",
    );

    // ── section 1: hosting accounts ──────────────────────────────────────
    doc.push_str("## 1. Set up hosting accounts\n\n");

    if needs_flyio(f) {
        doc.push_str(concat!(
            "### Fly.io (free tier)\n\n",
            "```sh\n",
            "# Install flyctl\n",
            "curl -L https://fly.io/install.sh | sh\n",
            "\n",
            "# Create account and log in\n",
            "fly auth signup   # or: fly auth login\n",
            "```\n\n",
            "All self-hosted services in this guide can be deployed with:\n\n",
            "```sh\n",
            "cd <service-dir>\n",
            "fly launch   # reads docker-compose.yml and creates fly.toml\n",
            "fly deploy\n",
            "```\n\n",
        ));
    }

    if needs_r2(f) {
        doc.push_str(concat!(
            "### Cloudflare R2 (free: 10 GB storage, free egress)\n\n",
            "Video and audio files can easily exceed free compute disk limits.\n",
            "Cloudflare R2 provides 10 GB free storage with zero egress fees.\n\n",
            "1. Sign up at <https://dash.cloudflare.com>\n",
            "2. Go to **R2 Object Storage** → **Create bucket**\n",
            "   - Bucket name: `your-project-media` (or similar)\n",
            "   - Region: Automatic\n",
            "3. Go to **Manage R2 API tokens** → **Create API token**\n",
            "   - Permissions: Object Read & Write\n",
            "   - Save the **Access Key ID** and **Secret Access Key**\n",
            "4. Note your **Account ID** from the R2 overview page\n\n",
            "Set these values in your service `.env` file:\n",
            "```\n",
            "R2_ENDPOINT=https://<account-id>.r2.cloudflarestorage.com\n",
            "R2_ACCESS_KEY_ID=<your-access-key-id>\n",
            "R2_SECRET_ACCESS_KEY=<your-secret-access-key>\n",
            "```\n\n",
        ));
    }

    // ── section 2: per-service steps ─────────────────────────────────────
    doc.push_str("## 2. Deploy services\n\n");

    if f.email == EmailChoice::Listmonk {
        doc.push_str(concat!(
            "### Listmonk (newsletter)\n\n",
            "```sh\n",
            "cd listmonk\n",
            "cp .env.listmonk.example .env.listmonk\n",
            "# Edit .env.listmonk — set DB_PASSWORD and SITE_URL\n",
            "docker compose --env-file .env.listmonk up -d\n",
            "```\n\n",
            "**First-time setup:**\n\n",
            "1. Visit your Listmonk URL and complete the setup wizard.\n",
            "2. Go to **Lists** → **New list** and create a subscriber list.\n",
            "3. Note the list ID (shown in the URL as `/lists/1/...` → ID is `1`).\n",
            "4. Add to your `.env`:\n\n",
            "```\n",
            "NEWSLETTER_DELIVERY_MODE=listmonk\n",
            "LISTMONK_API_URL=https://your-listmonk-instance.example.com\n",
            "LISTMONK_API_USERNAME=your-admin-username\n",
            "LISTMONK_API_PASSWORD=your-admin-password\n",
            "LISTMONK_LIST_ID=1\n",
            "```\n\n",
            "**Why Caddy?** Listmonk sends `X-Frame-Options: SAMEORIGIN` on every response.\n",
            "The Caddy proxy strips that header and replaces it with a `frame-ancestors` CSP\n",
            "scoped to your Astropress site, so the Listmonk admin embeds at `/ap-admin/services/email`.\n\n",
            "**Mailchimp migration:** Export from Mailchimp → Audience → Export Audience (CSV),\n",
            "convert to `[{\"email\": \"...\", \"name\": \"...\"}]` JSON, then POST to `/api/subscribers/import`.\n\n",
        ));
    }

    if f.cms == CmsChoice::Payload {
        doc.push_str(concat!(
            "### Payload CMS\n\n",
            "```sh\n",
            "cd payload\n",
            "cp .env.payload.example .env.payload\n",
            "# Edit .env.payload — set DB_PASSWORD and PAYLOAD_SECRET\n",
            "docker compose --env-file .env.payload up -d\n",
            "```\n\n",
            "Update `.env`:\n",
            "```\n",
            "PAYLOAD_URL=https://cms.yourdomain.com\n",
            "PAYLOAD_SECRET=<your-payload-secret>\n",
            "```\n\n",
        ));
    }

    if f.search == SearchChoice::Meilisearch {
        doc.push_str(concat!(
            "### Meilisearch (full-text search)\n\n",
            "```sh\n",
            "cd meilisearch\n",
            "cp .env.meilisearch.example .env.meilisearch\n",
            "# Edit .env.meilisearch — set MEILI_MASTER_KEY\n",
            "docker compose --env-file .env.meilisearch up -d\n",
            "```\n\n",
            "Update `.env`:\n",
            "```\n",
            "MEILISEARCH_URL=https://search.yourdomain.com\n",
            "MEILISEARCH_API_KEY=<your-meili-master-key>\n",
            "```\n\n",
        ));
    }

    if f.search == SearchChoice::Typesense {
        doc.push_str(concat!(
            "### Typesense (full-text search)\n\n",
            "```sh\n",
            "cd typesense\n",
            "cp .env.typesense.example .env.typesense\n",
            "# Edit .env.typesense — set TYPESENSE_API_KEY\n",
            "docker compose --env-file .env.typesense up -d\n",
            "```\n\n",
            "Update `.env`:\n",
            "```\n",
            "TYPESENSE_HOST=search.yourdomain.com\n",
            "TYPESENSE_PORT=443\n",
            "TYPESENSE_PROTOCOL=https\n",
            "TYPESENSE_API_KEY=<your-typesense-api-key>\n",
            "```\n\n",
            "Create a collection after deploy: `POST /collections` with your schema.\n",
            "See <https://typesense.org/docs/guide/> for indexing examples.\n\n",
        ));
    }

    if f.community == CommunityChoice::Remark42 {
        doc.push_str(concat!(
            "### Remark42 (comments)\n\n",
            "```sh\n",
            "cd remark42\n",
            "cp .env.remark42.example .env.remark42\n",
            "# Edit .env.remark42 — set REMARK_URL and REMARK_SECRET\n",
            "docker compose --env-file .env.remark42 up -d\n",
            "```\n\n",
            "Update `.env`:\n",
            "```\n",
            "REMARK42_URL=https://comments.yourdomain.com\n",
            "REMARK42_SITE_ID=remark\n",
            "```\n\n",
        ));
    }

    if f.forum == ForumChoice::Flarum {
        doc.push_str(concat!(
            "### Flarum (forum)\n\n",
            "```sh\n",
            "cd flarum\n",
            "cp .env.flarum.example .env.flarum\n",
            "# Edit .env.flarum — set DB_PASSWORD and FLARUM_BASE_URL\n",
            "docker compose --env-file .env.flarum up -d\n",
            "```\n\n",
            "Update `.env`:\n",
            "```\n",
            "FLARUM_URL=https://forum.yourdomain.com\n",
            "FLARUM_API_KEY=<create in Flarum admin panel under API Keys>\n",
            "```\n\n",
        ));
    }

    if f.forum == ForumChoice::Discourse {
        doc.push_str(concat!(
            "### Discourse (forum)\n\n",
            "> ⚠ **Heavy:** Discourse needs 2 GB RAM minimum (2 CPUs recommended).\n",
            "> Fly.io `performance-2x` machine or Railway Pro are required.\n",
            "> For lighter resource use, consider Flarum instead.\n\n",
            "Discourse officially recommends its own install script:\n\n",
            "```sh\n",
            "cd discourse\n",
            "cp .env.discourse.example .env.discourse\n",
            "# See: https://github.com/discourse/discourse/blob/main/docs/INSTALL-cloud.md\n",
            "docker compose --env-file .env.discourse up -d\n",
            "```\n\n",
        ));
    }

    if f.chat == ChatChoice::Tiledesk {
        doc.push_str(concat!(
            "### Tiledesk (live chat)\n\n",
            "```sh\n",
            "cd tiledesk\n",
            "cp .env.tiledesk.example .env.tiledesk\n",
            "# Edit .env.tiledesk — set JWT_SECRET and TILEDESK_URL\n",
            "docker compose --env-file .env.tiledesk up -d\n",
            "```\n\n",
            "Full compose with all services: <https://github.com/Tiledesk/tiledesk-deployment>\n\n",
        ));
    }

    if f.chat == ChatChoice::Chatwoot {
        doc.push_str(concat!(
            "### Chatwoot (customer support)\n\n",
            "```sh\n",
            "cd chatwoot\n",
            "cp .env.chatwoot.example .env.chatwoot\n",
            "# Edit .env.chatwoot — set DB_PASSWORD, SECRET_KEY_BASE, CHATWOOT_URL\n",
            "docker compose --env-file .env.chatwoot up -d\n",
            "# Run database migrations on first deploy:\n",
            "docker compose exec chatwoot-server bundle exec rails db:chatwoot_prepare\n",
            "```\n\n",
            "Update `.env`:\n",
            "```\n",
            "CHATWOOT_API_URL=https://support.yourdomain.com\n",
            "CHATWOOT_API_TOKEN=<create in Settings → Integrations → API Access Token>\n",
            "CHATWOOT_WEBSITE_TOKEN=<create in Settings → Inboxes → New Inbox → Website>\n",
            "```\n\n",
        ));
    }

    if f.payments == PaymentChoice::HyperSwitch {
        doc.push_str(concat!(
            "### HyperSwitch (payment router + Unified Checkout Web SDK)\n\n",
            "> Apache 2.0 | Rust server • MIT Web SDK — made by Juspay (India)\n\n",
            "```sh\n",
            "cd hyperswitch\n",
            "cp .env.hyperswitch.example .env.hyperswitch\n",
            "# Edit .env.hyperswitch — set DB_PASSWORD, JWT_SECRET, HYPERSWITCH_API_KEY, HYPERSWITCH_BASE_URL\n",
            "docker compose --env-file .env.hyperswitch up -d\n",
            "```\n\n",
            "**Connect payment providers** — open the HyperSwitch dashboard → **Connectors** and add the\n",
            "providers for your target markets. Enter API credentials from each provider's dashboard.\n\n",
            "| Region | Provider | Methods |\n",
            "|--------|----------|---------|\n",
            "| East Africa | Safaricom M-Pesa / Daraja | STK Push (phone → PIN on device), C2B, B2C |\n",
            "| West & Southern Africa | Flutterwave (NG, GH, ZA, TZ, UG + 20 more) | Mobile money (MTN, Airtel), USSD, bank transfer, cards |\n",
            "| West & Southern Africa | Paystack (NG, GH, KE, ZA) | Cards, bank transfer, USSD, mobile money |\n",
            "| India | Razorpay | UPI, IMPS, NEFT, cards, netbanking |\n",
            "| India | Cashfree | UPI, UPI QR, cards, wallets |\n",
            "| India | PayU | UPI, EMI, cards, wallets |\n",
            "| India | PhonePe | UPI via PhonePe switch |\n",
            "| Southeast Asia | Xendit (PH, ID) | GCash, Maya (PH) · OVO, GoPay, QRIS, bank VA (ID) |\n",
            "| Southeast Asia | Adyen (SG, MY, TH, VN, PH, ID) | GrabPay, PayNow (SG), PromptPay (TH), FPX/DuitNow (MY), QRIS (ID) |\n",
            "| Middle East & N. Africa | Noon (AE, SA, EG, JO) | Cards, mada (SA), Meeza (EG) |\n",
            "| Middle East & N. Africa | Checkout.com (AE, SA, KW, QA, BH, EG) | mada (SA), KNET (KW), BENEFIT (BH), Fawry (EG), cards |\n",
            "| Latin America | dLocal (BR, MX, AR, CL, CO, PE + 9 more) | PIX (BR), OXXO (MX), Boleto (BR), PSE (CO), bank transfer, cards |\n",
            "| Latin America | Ebanx (BR, MX, CO, AR, CL, PE) | PIX (BR), Boleto (BR), OXXO (MX), cards |\n",
            "| Latin America | PayU (BR, CO, PE) | PIX (BR), PSE (CO), Efecty (CO), cards |\n",
            "| Global | Stripe | Cards, Apple Pay, Google Pay |\n",
            "| Global | Adyen | Cards + all regional methods above |\n",
            "| Global | PayPal | PayPal, Venmo |\n",
            "| Global | Checkout.com | Cards, Apple Pay, digital wallets |\n\n",
            "**Add the publishable key** — go to **Developers → API Keys**, copy the publishable key\n",
            "and add it to `.env`:\n\n",
            "```\n",
            "HYPERSWITCH_PUBLISHABLE_KEY=<your-publishable-key>\n",
            "```\n\n",
            "**Checkout form** — `src/components/HyperCheckout.astro` is already scaffolded.\n",
            "It mounts the HyperSwitch Unified Checkout Web SDK (MIT), which auto-shows the right\n",
            "UI based on the connectors you've enabled and the user's device:\n\n",
            "- **M-Pesa**: phone-number field → Safaricom STK Push — PIN prompt on device, no redirect\n",
            "- **Mobile money (Flutterwave/Paystack)**: phone number or account selection flow\n",
            "- **UPI**: VPA (UPI ID) field + collect flow — Razorpay, Cashfree, PayU, PhonePe\n",
            "- **GrabPay / PromptPay / PIX / OXXO**: redirect or in-page QR based on provider\n",
            "- **Cards / Apple Pay / Google Pay**: standard card form or native payment sheet\n\n",
            "Full deploy guide: <https://docs.hyperswitch.io/hyperswitch-open-source/deploy-hyperswitch>\n\n",
        ));
    }

    if f.schedule == ScheduleChoice::Rallly {
        doc.push_str(concat!(
            "### Rallly (scheduling polls)\n\n",
            "```sh\n",
            "cd rallly\n",
            "cp .env.rallly.example .env.rallly\n",
            "# Edit .env.rallly — set DB_PASSWORD, SECRET_PASSWORD, RALLLY_URL, and SMTP vars\n",
            "docker compose --env-file .env.rallly up -d\n",
            "```\n\n",
        ));
    }

    if f.schedule == ScheduleChoice::CalCom {
        doc.push_str(concat!(
            "### Cal.com (booking + calendar)\n\n",
            "> Free cloud tier at <https://cal.com> — recommended for most users.\n\n",
            "```sh\n",
            "cd calcom\n",
            "cp .env.calcom.example .env.calcom\n",
            "# Edit .env.calcom — set all required vars\n",
            "docker compose --env-file .env.calcom up -d\n",
            "```\n\n",
            "Full guide: <https://cal.com/docs/self-hosting/docker>\n\n",
        ));
    }

    if f.notify == NotifyChoice::Gotify {
        doc.push_str(concat!(
            "### Gotify (push notifications)\n\n",
            "```sh\n",
            "cd gotify\n",
            "cp .env.gotify.example .env.gotify\n",
            "# Edit .env.gotify — set GOTIFY_ADMIN_PASS\n",
            "docker compose --env-file .env.gotify up -d\n",
            "```\n\n",
            "After deploying, create an application in the Gotify UI to get an app token.\n",
            "Update `.env`:\n",
            "```\n",
            "GOTIFY_URL=https://notify.yourdomain.com\n",
            "GOTIFY_APP_TOKEN=<token-from-gotify-ui>\n",
            "```\n\n",
        ));
    }

    append_more_services(&mut doc, f);

    doc.push_str("---\n\n_Generated by `astropress new`_\n");
    Some(doc)
}
