//! `SERVICES.md` generator: per-service deploy instructions.
//!
//! Orchestrated by `service_docs::build_services_doc()` — this module owns
//! the string-builder for the unified markdown file. Later service sections
//! (commerce, forms, video, podcast, events, transactional email, status,
//! knowledge base, CRM, SSO, courses) live in `markdown_more.rs` to keep
//! each file under the 300-line arch-lint warning.

use crate::features::{
    AllFeatures, CmsChoice, EmailChoice, PodcastChoice, SearchChoice,
    VideoChoice,
};
use super::service_compose_stubs;

#[path = "markdown_more.rs"]
mod markdown_more;

use markdown_more::append_more_services;

#[path = "markdown_mid.rs"]
mod markdown_mid;

fn needs_flyio(f: &AllFeatures) -> bool {
    !service_compose_stubs(f).is_empty()
}

fn needs_r2(f: &AllFeatures) -> bool {
    f.video == VideoChoice::PeerTube || f.podcast == PodcastChoice::Castopod
}

/// Generates a unified `SERVICES.md` setup guide covering:
/// 1. Hosting accounts to set up first (Fly.io, Cloudflare R2 if needed)
/// 2. Per-service deploy steps for every selected self-hosted service
///
/// Returns `None` if no self-hosted services were selected.
pub(crate) fn build_services_doc(f: &AllFeatures) -> Option<String> {
    if service_compose_stubs(f).is_empty() {
        return None;
    }
    let mut doc = String::from(
        "# Services Setup Guide\n\
         \n\
         Generated by `astropress new`. Deploy your services in this order:\n\
         first set up your hosting accounts, then deploy each service.\n\
         \n",
    );

    // ── section 1: hosting accounts ──────────────────────────────────────
    doc.push_str("## 1. Set up hosting accounts\n\n");

    if needs_flyio(f) {
        doc.push_str(concat!(
            "### Fly.io (free tier)\n\n",
            "```sh\n",
            "# Install flyctl\n",
            "curl -L https://fly.io/install.sh | sh\n",
            "\n",
            "# Create account and log in\n",
            "fly auth signup   # or: fly auth login\n",
            "```\n\n",
            "All self-hosted services in this guide can be deployed with:\n\n",
            "```sh\n",
            "cd <service-dir>\n",
            "fly launch   # reads docker-compose.yml and creates fly.toml\n",
            "fly deploy\n",
            "```\n\n",
        ));
    }

    if needs_r2(f) {
        doc.push_str(concat!(
            "### Cloudflare R2 (free: 10 GB storage, free egress)\n\n",
            "Video and audio files can easily exceed free compute disk limits.\n",
            "Cloudflare R2 provides 10 GB free storage with zero egress fees.\n\n",
            "1. Sign up at <https://dash.cloudflare.com>\n",
            "2. Go to **R2 Object Storage** → **Create bucket**\n",
            "   - Bucket name: `your-project-media` (or similar)\n",
            "   - Region: Automatic\n",
            "3. Go to **Manage R2 API tokens** → **Create API token**\n",
            "   - Permissions: Object Read & Write\n",
            "   - Save the **Access Key ID** and **Secret Access Key**\n",
            "4. Note your **Account ID** from the R2 overview page\n\n",
            "Set these values in your service `.env` file:\n",
            "```\n",
            "R2_ENDPOINT=https://<account-id>.r2.cloudflarestorage.com\n",
            "R2_ACCESS_KEY_ID=<your-access-key-id>\n",
            "R2_SECRET_ACCESS_KEY=<your-secret-access-key>\n",
            "```\n\n",
        ));
    }

    // ── section 2: per-service steps ─────────────────────────────────────
    doc.push_str("## 2. Deploy services\n\n");

    if f.email == EmailChoice::Listmonk {
        doc.push_str(concat!(
            "### Listmonk (newsletter)\n\n",
            "```sh\n",
            "cd listmonk\n",
            "cp .env.listmonk.example .env.listmonk\n",
            "# Edit .env.listmonk — set DB_PASSWORD and SITE_URL\n",
            "docker compose --env-file .env.listmonk up -d\n",
            "```\n\n",
            "**First-time setup:**\n\n",
            "1. Visit your Listmonk URL and complete the setup wizard.\n",
            "2. Go to **Lists** → **New list** and create a subscriber list.\n",
            "3. Note the list ID (shown in the URL as `/lists/1/...` → ID is `1`).\n",
            "4. Add to your `.env`:\n\n",
            "```\n",
            "NEWSLETTER_DELIVERY_MODE=listmonk\n",
            "LISTMONK_API_URL=https://your-listmonk-instance.example.com\n",
            "LISTMONK_API_USERNAME=your-admin-username\n",
            "LISTMONK_API_PASSWORD=your-admin-password\n",
            "LISTMONK_LIST_ID=1\n",
            "```\n\n",
            "**Why Caddy?** Listmonk sends `X-Frame-Options: SAMEORIGIN` on every response.\n",
            "The Caddy proxy strips that header and replaces it with a `frame-ancestors` CSP\n",
            "scoped to your Astropress site, so the Listmonk admin embeds at `/ap-admin/services/email`.\n\n",
            "**Mailchimp migration:** Export from Mailchimp → Audience → Export Audience (CSV),\n",
            "convert to `[{\"email\": \"...\", \"name\": \"...\"}]` JSON, then POST to `/api/subscribers/import`.\n\n",
        ));
    }

    if f.cms == CmsChoice::Payload {
        doc.push_str(concat!(
            "### Payload CMS\n\n",
            "```sh\n",
            "cd payload\n",
            "cp .env.payload.example .env.payload\n",
            "# Edit .env.payload — set DB_PASSWORD and PAYLOAD_SECRET\n",
            "docker compose --env-file .env.payload up -d\n",
            "```\n\n",
            "Update `.env`:\n",
            "```\n",
            "PAYLOAD_URL=https://cms.yourdomain.com\n",
            "PAYLOAD_SECRET=<your-payload-secret>\n",
            "```\n\n",
        ));
    }

    if f.search == SearchChoice::Meilisearch {
        doc.push_str(concat!(
            "### Meilisearch (full-text search)\n\n",
            "```sh\n",
            "cd meilisearch\n",
            "cp .env.meilisearch.example .env.meilisearch\n",
            "# Edit .env.meilisearch — set MEILI_MASTER_KEY\n",
            "docker compose --env-file .env.meilisearch up -d\n",
            "```\n\n",
            "Update `.env`:\n",
            "```\n",
            "MEILISEARCH_URL=https://search.yourdomain.com\n",
            "MEILISEARCH_API_KEY=<your-meili-master-key>\n",
            "```\n\n",
        ));
    }

    if f.search == SearchChoice::Typesense {
        doc.push_str(concat!(
            "### Typesense (full-text search)\n\n",
            "```sh\n",
            "cd typesense\n",
            "cp .env.typesense.example .env.typesense\n",
            "# Edit .env.typesense — set TYPESENSE_API_KEY\n",
            "docker compose --env-file .env.typesense up -d\n",
            "```\n\n",
            "Update `.env`:\n",
            "```\n",
            "TYPESENSE_HOST=search.yourdomain.com\n",
            "TYPESENSE_PORT=443\n",
            "TYPESENSE_PROTOCOL=https\n",
            "TYPESENSE_API_KEY=<your-typesense-api-key>\n",
            "```\n\n",
            "Create a collection after deploy: `POST /collections` with your schema.\n",
            "See <https://typesense.org/docs/guide/> for indexing examples.\n\n",
        ));
    }

    markdown_mid::append_mid_services(&mut doc, f);

    append_more_services(&mut doc, f);

    doc.push_str("---\n\n_Generated by `astropress new`_\n");
    Some(doc)
}
