//! Video and podcast hosting services.

// ── PeerTube ──────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_PEERTUBE: &str = concat!(
    "# PeerTube — self-hosted video with ActivityPub (AGPL 3.0).\n",
    "# ⚠ Video files need object storage (Cloudflare R2 or Tigris) — local disk fills up fast.\n",
    "# Full guide: https://docs.joinpeertube.org/install/docker\n",
    "# Usage: cp .env.peertube.example .env.peertube && docker compose --env-file .env.peertube up -d\n",
    "services:\n",
    "  peertube:\n",
    "    image: chocobozzz/peertube:production-bookworm\n",
    "    ports:\n",
    "      - \"9000:9000\"\n",
    "      - \"1935:1935\"  # RTMP live streaming\n",
    "    environment:\n",
    "      PEERTUBE_DB_HOSTNAME: db\n",
    "      PEERTUBE_DB_USERNAME: peertube\n",
    "      PEERTUBE_DB_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.peertube}\"\n",
    "      PEERTUBE_DB_NAME: peertube\n",
    "      PEERTUBE_REDIS_HOSTNAME: redis\n",
    "      PEERTUBE_SMTP_HOSTNAME: \"${SMTP_HOST}\"\n",
    "      PEERTUBE_SMTP_PORT: \"${SMTP_PORT:-587}\"\n",
    "      PEERTUBE_SMTP_USERNAME: \"${SMTP_USER}\"\n",
    "      PEERTUBE_SMTP_PASSWORD: \"${SMTP_PASSWORD}\"\n",
    "      PEERTUBE_SMTP_FROM: \"${SMTP_FROM}\"\n",
    "      PEERTUBE_WEBSERVER_HOSTNAME: \"${PEERTUBE_HOSTNAME:?set PEERTUBE_HOSTNAME in .env.peertube}\"\n",
    "      PEERTUBE_OBJECT_STORAGE_ENABLED: \"${OBJECT_STORAGE_ENABLED:-false}\"\n",
    "      PEERTUBE_OBJECT_STORAGE_ENDPOINT: \"${R2_ENDPOINT}\"\n",
    "      PEERTUBE_OBJECT_STORAGE_CREDENTIALS_ACCESS_KEY_ID: \"${R2_ACCESS_KEY_ID}\"\n",
    "      PEERTUBE_OBJECT_STORAGE_CREDENTIALS_SECRET_ACCESS_KEY: \"${R2_SECRET_ACCESS_KEY}\"\n",
    "    volumes:\n",
    "      - peertube_data:/data\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "      redis:\n",
    "        condition: service_started\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    image: postgres:16-alpine\n",
    "    environment:\n",
    "      POSTGRES_USER: peertube\n",
    "      POSTGRES_PASSWORD: \"${DB_PASSWORD}\"\n",
    "      POSTGRES_DB: peertube\n",
    "    volumes:\n",
    "      - peertube_db:/var/lib/postgresql/data\n",
    "    healthcheck:\n",
    "      test: [\"CMD-SHELL\", \"pg_isready -U peertube\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 5\n",
    "    restart: unless-stopped\n",
    "\n",
    "  redis:\n",
    "    image: redis:7-alpine\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  peertube_data:\n",
    "  peertube_db:\n",
);
pub(super) const ENV_PEERTUBE: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "PEERTUBE_HOSTNAME=video.yourdomain.com\n",
    "SMTP_HOST=smtp-relay.brevo.com\n",
    "SMTP_PORT=587\n",
    "SMTP_USER=your-brevo-login@example.com\n",
    "SMTP_PASSWORD=your-brevo-smtp-key\n",
    "SMTP_FROM=noreply@yourdomain.com\n",
    "# Object storage (Cloudflare R2 — free 10 GB/month egress)\n",
    "OBJECT_STORAGE_ENABLED=true\n",
    "R2_ENDPOINT=https://<account-id>.r2.cloudflarestorage.com\n",
    "R2_ACCESS_KEY_ID=replace-me\n",
    "R2_SECRET_ACCESS_KEY=replace-me\n",
);


// ── Castopod ──────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_CASTOPOD: &str = concat!(
    "# Castopod — self-hosted podcast hosting (AGPL 3.0).\n",
    "# ⚠ Audio files need object storage (Cloudflare R2 or Tigris) — local disk fills up fast.\n",
    "# Free tier: Fly.io shared-cpu-1x with 512 MB.\n",
    "# Usage: cp .env.castopod.example .env.castopod && docker compose --env-file .env.castopod up -d\n",
    "services:\n",
    "  castopod:\n",
    "    image: castopod/castopod:latest\n",
    "    ports:\n",
    "      - \"8000:8000\"\n",
    "    environment:\n",
    "      CP_BASEURL: \"${CASTOPOD_URL:?set CASTOPOD_URL in .env.castopod}\"\n",
    "      CP_DATABASE_HOSTNAME: db\n",
    "      CP_DATABASE_NAME: castopod\n",
    "      CP_DATABASE_USERNAME: castopod\n",
    "      CP_DATABASE_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.castopod}\"\n",
    "      CP_MEDIA_BASE_URL: \"${MEDIA_BASE_URL}\"\n",
    "      CP_EMAIL_SMTPHost: \"${SMTP_HOST}\"\n",
    "      CP_EMAIL_SMTPPort: \"${SMTP_PORT:-587}\"\n",
    "      CP_EMAIL_SMTPCrypto: tls\n",
    "      CP_EMAIL_SMTPUser: \"${SMTP_USER}\"\n",
    "      CP_EMAIL_SMTPPass: \"${SMTP_PASSWORD}\"\n",
    "      CP_EMAIL_fromEmail: \"${SMTP_FROM}\"\n",
    "    volumes:\n",
    "      - castopod_media:/var/www/castopod/public/media\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    # mariadb:11 uses ~100 MB idle vs MySQL 8's ~300 MB — better fit for free tiers.\n",
    "    image: mariadb:11\n",
    "    environment:\n",
    "      MYSQL_DATABASE: castopod\n",
    "      MYSQL_USER: castopod\n",
    "      MYSQL_PASSWORD: \"${DB_PASSWORD}\"\n",
    "      MYSQL_ROOT_PASSWORD: \"${DB_ROOT_PASSWORD:-rootpass}\"\n",
    "    volumes:\n",
    "      - castopod_db:/var/lib/mysql\n",
    "    healthcheck:\n",
    "      test: [\"CMD\", \"mysqladmin\", \"ping\", \"-h\", \"localhost\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 10\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  castopod_media:\n",
    "  castopod_db:\n",
);
pub(super) const ENV_CASTOPOD: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "DB_ROOT_PASSWORD=change-me-root\n",
    "CASTOPOD_URL=https://podcast.yourdomain.com\n",
    "MEDIA_BASE_URL=https://podcast.yourdomain.com\n",
    "SMTP_HOST=smtp-relay.brevo.com\n",
    "SMTP_PORT=587\n",
    "SMTP_USER=your-brevo-login@example.com\n",
    "SMTP_PASSWORD=your-brevo-smtp-key\n",
    "SMTP_FROM=noreply@yourdomain.com\n",
);

