//! Scheduling and event management services.

// ── Rallly ────────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_RALLLY: &str = concat!(
    "# Rallly — availability polling / group scheduling (MIT).\n",
    "# Usage: cp .env.rallly.example .env.rallly && docker compose --env-file .env.rallly up -d\n",
    "services:\n",
    "  rallly:\n",
    "    image: lukevella/rallly:latest\n",
    "    ports:\n",
    "      - \"3000:3000\"\n",
    "    environment:\n",
    "      DATABASE_URL: \"postgres://rallly:${DB_PASSWORD}@db:5432/rallly\"\n",
    "      SECRET_PASSWORD: \"${SECRET_PASSWORD:?set SECRET_PASSWORD in .env.rallly}\"\n",
    "      NEXT_PUBLIC_BASE_URL: \"${RALLLY_URL:?set RALLLY_URL in .env.rallly}\"\n",
    "      SMTP_HOST: \"${SMTP_HOST}\"\n",
    "      SMTP_PORT: \"${SMTP_PORT:-587}\"\n",
    "      SMTP_USER: \"${SMTP_USER}\"\n",
    "      SMTP_PWD: \"${SMTP_PASSWORD}\"\n",
    "      SUPPORT_EMAIL: \"${SUPPORT_EMAIL}\"\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    image: postgres:16-alpine\n",
    "    environment:\n",
    "      POSTGRES_USER: rallly\n",
    "      POSTGRES_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.rallly}\"\n",
    "      POSTGRES_DB: rallly\n",
    "    volumes:\n",
    "      - rallly_db:/var/lib/postgresql/data\n",
    "    healthcheck:\n",
    "      test: [\"CMD-SHELL\", \"pg_isready -U rallly\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 5\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  rallly_db:\n",
);
pub(super) const ENV_RALLLY: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "SECRET_PASSWORD=change-me-long-random-string\n",
    "RALLLY_URL=https://schedule.yourdomain.com\n",
    "SMTP_HOST=smtp-relay.brevo.com\n",
    "SMTP_PORT=587\n",
    "SMTP_USER=your-brevo-login@example.com\n",
    "SMTP_PASSWORD=your-brevo-smtp-key\n",
    "SUPPORT_EMAIL=support@yourdomain.com\n",
);


// ── Cal.com ───────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_CALCOM: &str = concat!(
    "# Cal.com — open-source scheduling (AGPL 3.0).\n",
    "# Official self-host guide: https://cal.com/docs/self-hosting/docker\n",
    "# Free cloud tier available at https://cal.com (recommended for small teams).\n",
    "# Usage: cp .env.calcom.example .env.calcom && docker compose --env-file .env.calcom up -d\n",
    "services:\n",
    "  calcom:\n",
    "    image: calcom/cal.com:latest\n",
    "    ports:\n",
    "      - \"3000:3000\"\n",
    "    environment:\n",
    "      DATABASE_URL: \"postgresql://calcom:${DB_PASSWORD}@db:5432/calcom\"\n",
    "      NEXTAUTH_SECRET: \"${NEXTAUTH_SECRET:?set NEXTAUTH_SECRET in .env.calcom}\"\n",
    "      CALENDSO_ENCRYPTION_KEY: \"${ENCRYPTION_KEY:?set ENCRYPTION_KEY in .env.calcom}\"\n",
    "      NEXT_PUBLIC_WEBAPP_URL: \"${CALCOM_URL:?set CALCOM_URL in .env.calcom}\"\n",
    "      EMAIL_FROM: \"${EMAIL_FROM}\"\n",
    "      EMAIL_SERVER_HOST: \"${SMTP_HOST}\"\n",
    "      EMAIL_SERVER_PORT: \"${SMTP_PORT:-587}\"\n",
    "      EMAIL_SERVER_USER: \"${SMTP_USER}\"\n",
    "      EMAIL_SERVER_PASSWORD: \"${SMTP_PASSWORD}\"\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    image: postgres:16-alpine\n",
    "    environment:\n",
    "      POSTGRES_USER: calcom\n",
    "      POSTGRES_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.calcom}\"\n",
    "      POSTGRES_DB: calcom\n",
    "    volumes:\n",
    "      - calcom_db:/var/lib/postgresql/data\n",
    "    healthcheck:\n",
    "      test: [\"CMD-SHELL\", \"pg_isready -U calcom\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 5\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  calcom_db:\n",
);
pub(super) const ENV_CALCOM: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "NEXTAUTH_SECRET=change-me-32-char-random-string\n",
    "ENCRYPTION_KEY=change-me-32-char-random-string\n",
    "CALCOM_URL=https://cal.yourdomain.com\n",
    "EMAIL_FROM=noreply@yourdomain.com\n",
    "SMTP_HOST=smtp-relay.brevo.com\n",
    "SMTP_PORT=587\n",
    "SMTP_USER=your-brevo-login@example.com\n",
    "SMTP_PASSWORD=your-brevo-smtp-key\n",
);


// ── Hi.Events ─────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_HIEVENTS: &str = concat!(
    "# Hi.Events — event management + ticketing (AGPL 3.0).\n",
    "# Usage: cp .env.hievents.example .env.hievents && docker compose --env-file .env.hievents up -d\n",
    "services:\n",
    "  hievents:\n",
    "    image: drizzer/hievents:latest\n",
    "    ports:\n",
    "      - \"8080:8080\"\n",
    "    environment:\n",
    "      DB_CONNECTION: pgsql\n",
    "      DB_HOST: db\n",
    "      DB_PORT: \"5432\"\n",
    "      DB_DATABASE: hievents\n",
    "      DB_USERNAME: hievents\n",
    "      DB_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.hievents}\"\n",
    "      APP_KEY: \"${APP_KEY:?set APP_KEY in .env.hievents}\"\n",
    "      APP_URL: \"${HIEVENTS_URL:?set HIEVENTS_URL in .env.hievents}\"\n",
    "      MAIL_MAILER: smtp\n",
    "      MAIL_HOST: \"${SMTP_HOST}\"\n",
    "      MAIL_PORT: \"${SMTP_PORT:-587}\"\n",
    "      MAIL_USERNAME: \"${SMTP_USER}\"\n",
    "      MAIL_PASSWORD: \"${SMTP_PASSWORD}\"\n",
    "      MAIL_FROM_ADDRESS: \"${SMTP_FROM}\"\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    image: postgres:16-alpine\n",
    "    environment:\n",
    "      POSTGRES_USER: hievents\n",
    "      POSTGRES_PASSWORD: \"${DB_PASSWORD}\"\n",
    "      POSTGRES_DB: hievents\n",
    "    volumes:\n",
    "      - hievents_db:/var/lib/postgresql/data\n",
    "    healthcheck:\n",
    "      test: [\"CMD-SHELL\", \"pg_isready -U hievents\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 5\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  hievents_db:\n",
);
pub(super) const ENV_HIEVENTS: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "APP_KEY=base64:change-me-32-char-random-string\n",
    "HIEVENTS_URL=https://events.yourdomain.com\n",
    "SMTP_HOST=smtp-relay.brevo.com\n",
    "SMTP_PORT=587\n",
    "SMTP_USER=your-brevo-login@example.com\n",
    "SMTP_PASSWORD=your-brevo-smtp-key\n",
    "SMTP_FROM=noreply@yourdomain.com\n",
);


// ── Pretix ────────────────────────────────────────────────────────────────────

pub(super) const COMPOSE_PRETIX: &str = concat!(
    "# Pretix — event ticketing with seating charts (Apache 2.0).\n",
    "# Full guide: https://docs.pretix.eu/en/latest/admin/installation/docker_smallscale.html\n",
    "# Usage: cp .env.pretix.example .env.pretix && docker compose --env-file .env.pretix up -d\n",
    "services:\n",
    "  pretix:\n",
    "    image: pretix/standalone:stable\n",
    "    ports:\n",
    "      - \"80:80\"\n",
    "    environment:\n",
    "      PRETIX_SITE_URL: \"${PRETIX_URL:?set PRETIX_URL in .env.pretix}\"\n",
    "      PRETIX_DATABASE_BACKEND: postgresql\n",
    "      PRETIX_DATABASE_HOST: db\n",
    "      PRETIX_DATABASE_NAME: pretix\n",
    "      PRETIX_DATABASE_USER: pretix\n",
    "      PRETIX_DATABASE_PASSWORD: \"${DB_PASSWORD:?set DB_PASSWORD in .env.pretix}\"\n",
    "      PRETIX_REDIS_LOCATION: \"redis://redis:6379/0\"\n",
    "      PRETIX_CELERY_BROKER: \"redis://redis:6379/1\"\n",
    "      PRETIX_MAIL_FROM: \"${SMTP_FROM}\"\n",
    "      PRETIX_MAIL_HOST: \"${SMTP_HOST}\"\n",
    "      PRETIX_MAIL_PORT: \"${SMTP_PORT:-587}\"\n",
    "      PRETIX_MAIL_TLS: \"true\"\n",
    "      PRETIX_MAIL_USER: \"${SMTP_USER}\"\n",
    "      PRETIX_MAIL_PASSWORD: \"${SMTP_PASSWORD}\"\n",
    "    volumes:\n",
    "      - pretix_data:/data\n",
    "    depends_on:\n",
    "      db:\n",
    "        condition: service_healthy\n",
    "      redis:\n",
    "        condition: service_started\n",
    "    restart: unless-stopped\n",
    "\n",
    "  db:\n",
    "    image: postgres:16-alpine\n",
    "    environment:\n",
    "      POSTGRES_USER: pretix\n",
    "      POSTGRES_PASSWORD: \"${DB_PASSWORD}\"\n",
    "      POSTGRES_DB: pretix\n",
    "    volumes:\n",
    "      - pretix_db:/var/lib/postgresql/data\n",
    "    healthcheck:\n",
    "      test: [\"CMD-SHELL\", \"pg_isready -U pretix\"]\n",
    "      interval: 5s\n",
    "      timeout: 5s\n",
    "      retries: 5\n",
    "    restart: unless-stopped\n",
    "\n",
    "  redis:\n",
    "    image: redis:7-alpine\n",
    "    restart: unless-stopped\n",
    "\n",
    "volumes:\n",
    "  pretix_data:\n",
    "  pretix_db:\n",
);
pub(super) const ENV_PRETIX: &str = concat!(
    "DB_PASSWORD=change-me\n",
    "PRETIX_URL=https://tickets.yourdomain.com\n",
    "SMTP_HOST=smtp-relay.brevo.com\n",
    "SMTP_PORT=587\n",
    "SMTP_USER=your-brevo-login@example.com\n",
    "SMTP_PASSWORD=your-brevo-smtp-key\n",
    "SMTP_FROM=noreply@yourdomain.com\n",
);

