//! Docker Compose stubs for social media cross-posting services.

pub(super) const COMPOSE_POSTIZ: &str = concat!(
    "# Postiz — AGPL 3.0  https://github.com/gitroomhq/postiz-app\n",
    "# Cross-post to LinkedIn, Bluesky, Mastodon, Twitter/X, Instagram, TikTok, Pinterest,\n",
    "# Reddit, Threads, Facebook, and YouTube from a single scheduling dashboard.\n",
    "services:\n",
    "  postiz:\n",
    "    image: ghcr.io/gitroomhq/postiz-app:latest\n",
    "    restart: unless-stopped\n",
    "    ports:\n",
    "      - \"5000:5000\"\n",
    "    env_file: .env.postiz\n",
    "    volumes:\n",
    "      - postiz_uploads:/uploads\n",
    "    depends_on:\n",
    "      - postiz_db\n",
    "      - postiz_redis\n",
    "\n",
    "  postiz_db:\n",
    "    image: postgres:16-alpine\n",
    "    restart: unless-stopped\n",
    "    env_file: .env.postiz\n",
    "    environment:\n",
    "      POSTGRES_DB: postiz\n",
    "      POSTGRES_USER: postiz\n",
    "      POSTGRES_PASSWORD: ${POSTIZ_DB_PASSWORD}\n",
    "    volumes:\n",
    "      - postiz_db_data:/var/lib/postgresql/data\n",
    "\n",
    "  postiz_redis:\n",
    "    image: redis:7-alpine\n",
    "    restart: unless-stopped\n",
    "    volumes:\n",
    "      - postiz_redis_data:/data\n",
    "\n",
    "volumes:\n",
    "  postiz_uploads:\n",
    "  postiz_db_data:\n",
    "  postiz_redis_data:\n",
);

pub(super) const ENV_POSTIZ: &str = concat!(
    "# Postiz — social media cross-posting scheduler (AGPL 3.0)\n",
    "# https://github.com/gitroomhq/postiz-app\n",
    "#\n",
    "# Supported platforms: LinkedIn, Bluesky, Mastodon, Twitter/X, Instagram,\n",
    "#   TikTok, Pinterest, Reddit, Threads, Facebook, YouTube.\n",
    "#\n",
    "# After deploying, log in and connect each platform at:\n",
    "#   http://localhost:5000/settings/socials\n",
    "\n",
    "MAIN_URL=http://localhost:5000\n",
    "FRONTEND_URL=http://localhost:5000\n",
    "BACKEND_INTERNAL_URL=http://postiz:5000\n",
    "IS_GENERAL=true\n",
    "\n",
    "# Database (must match POSTGRES_PASSWORD in docker-compose.yml)\n",
    "POSTIZ_DB_PASSWORD=replace-me\n",
    "DATABASE_URL=postgresql://postiz:replace-me@postiz_db:5432/postiz\n",
    "\n",
    "# Redis\n",
    "REDIS_URL=redis://postiz_redis:6379\n",
    "\n",
    "# Auth\n",
    "JWT_SECRET=replace-me-with-a-long-random-string\n",
    "\n",
    "# Storage (local upload directory inside the container)\n",
    "STORAGE_PROVIDER=local\n",
    "UPLOAD_DIRECTORY=/uploads\n",
);

pub(super) const COMPOSE_MIXPOST: &str = concat!(
    "# Mixpost — MIT (community edition)  https://github.com/inovector/mixpost\n",
    "# Schedule and publish to Twitter/X, Facebook, Instagram, LinkedIn, Pinterest,\n",
    "# TikTok, and Mastodon.\n",
    "services:\n",
    "  mixpost:\n",
    "    image: inovector/mixpost:latest\n",
    "    restart: unless-stopped\n",
    "    ports:\n",
    "      - \"8080:80\"\n",
    "    env_file: .env.mixpost\n",
    "    depends_on:\n",
    "      - mixpost_db\n",
    "      - mixpost_redis\n",
    "\n",
    "  mixpost_db:\n",
    "    image: postgres:16-alpine\n",
    "    restart: unless-stopped\n",
    "    environment:\n",
    "      POSTGRES_DB: mixpost\n",
    "      POSTGRES_USER: mixpost\n",
    "      POSTGRES_PASSWORD: ${MIXPOST_DB_PASSWORD}\n",
    "    volumes:\n",
    "      - mixpost_db_data:/var/lib/postgresql/data\n",
    "\n",
    "  mixpost_redis:\n",
    "    image: redis:7-alpine\n",
    "    restart: unless-stopped\n",
    "    volumes:\n",
    "      - mixpost_redis_data:/data\n",
    "\n",
    "volumes:\n",
    "  mixpost_db_data:\n",
    "  mixpost_redis_data:\n",
);

pub(super) const ENV_MIXPOST: &str = concat!(
    "# Mixpost — social media scheduler (MIT community edition)\n",
    "# https://github.com/inovector/mixpost\n",
    "#\n",
    "# Supported platforms: Twitter/X, Facebook, Instagram, LinkedIn,\n",
    "#   Pinterest, TikTok, Mastodon.\n",
    "# Note: Bluesky is not supported in the community edition.\n",
    "#\n",
    "# After deploying, open http://localhost:8080 to create your account.\n",
    "\n",
    "APP_URL=http://localhost:8080\n",
    "APP_KEY=replace-me-with-32-char-random-string\n",
    "\n",
    "# Database (must match POSTGRES_PASSWORD in docker-compose.yml)\n",
    "MIXPOST_DB_PASSWORD=replace-me\n",
    "DB_HOST=mixpost_db\n",
    "DB_PORT=5432\n",
    "DB_DATABASE=mixpost\n",
    "DB_USERNAME=mixpost\n",
    "DB_PASSWORD=replace-me\n",
    "\n",
    "# Redis\n",
    "REDIS_HOST=mixpost_redis\n",
    "REDIS_PORT=6379\n",
);
